### ISSUE TITLE
Implement `countOdd`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#10]

**Comment by KUNAL1612** [comment]
Want to get started but I have no idea what the issue is. Mind elaborating?

**Comment by rgehan** [comment]
Look at the `src/countOdd.test.js` file, you have to implement `countOdd.js` so that the tests pass!

I'll mark it as assigned!

**Comment by KUNAL1612** [comment]
Hello. After a lot of head scratching I have made sure that the countOdd.js file is correct and tested it with yarn test. My question is, what am I supposed to now with regards to changing the test data?

**Comment by rgehan** [comment]
You can now open a pull request, we'll review it and if it matches all the rules we'll merge it!

**Comment by KUNAL1612** [comment]
Minor question: How do I check the checkboxes in the pull request description?
