### ISSUE TITLE
Implement `pinValidator`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#100]
### pinValidator

**Link to the PR that adds this test case**: #41 
**Where to implement**: `src/pinValidator.js`
**Where are the tests**: `src/pinValidator.test.js`

Thanks :heart:

**Comment by 0c0de** [comment]
I'll take it :smile:

**Comment by rgehan** [comment]
Go ahead

**Comment by kumaran-14** [comment]
Can i take this?

**Comment by cptjacky** [comment]
@kumaran-14 same there, check the labels..

**Comment by 0c0de** [comment]
Sorry I forgot to say that when I wrote that I was on college so I was unable to do it :sweat_smile:
