### ISSUE TITLE
Implement isCircularPrime

### ISSUE THREAD

**Issue by nip10** [rgehan/hacktoberfest-2k18-katas#1005]
# isCircularPrime

### Link to the PR that adds this test case:

#1007 

### Where to implement:

`src/isCircularPrime.js`

### Where are the tests:

`src/isCircularPrime.test.js`

### Description (optional):

A circular prime is a prime number with the property that the number generated at each intermediate step when cyclically permuting its (base 10) digits will be prime. ([source](https://en.wikipedia.org/wiki/Circular_prime))

Example: The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @leodevo, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
