### ISSUE TITLE
n-th sum nine

### ISSUE THREAD

**Issue by jeanbenitez** [rgehan/hacktoberfest-2k18-katas#1008]
# nthSumNine

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1038

### Where to implement:

`src/nthSumNine.js`

### Where are the tests:

`src/nthSumNine.test.js`

### Description (optional):

Given an integer value n, where 0 < n < 50, find out the n-th positive integer whose sum is 9.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @mphan6, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by mphan6** [comment]
On second thought, the test cases don't make sense.
@jeanbenitez  Why wouldn't the next positive integer whose digit sum is 9, not 9?

**Comment by jeanbenitez** [comment]
Ok, you're right, ignore the 9 as an obvious solution, and make your solution be valid for the test cases I've put ;)

**Comment by mphan6** [comment]
I'm still not understanding, looking at the next test case with 12, why wouldn't it be 126?

**Comment by jeanbenitez** [comment]
Yes! Damn! My bad... We need update those test cases!

**Comment by jeanbenitez** [comment]
```es6
expect(nthSumNine(1)).toEqual(9);
expect(nthSumNine(12)).toEqual(117);
expect(nthSumNine(18)).toEqual(171);
expect(nthSumNine(33)).toEqual(351);
expect(nthSumNine(47)).toEqual(612);

**Comment by jeanbenitez** [comment]
You can fix the test cases, @rgehan will approve your PR ;)
