### ISSUE TITLE
Implement luckyNumbers

### ISSUE THREAD

**Issue by xtangle** [rgehan/hacktoberfest-2k18-katas#1023]
# [luckyNumbers]

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1022

### Where to implement:

`src/luckyNumbers.js`

### Where are the tests:

`src/luckyNumbers.test.js`

### Description (optional):

A 'lucky' number is a natural number generated by a sieve, similar to how prime numbers are generated,
but instead of eliminating numbers based on their value, it eliminates them based on their position in
the remaining set. They are generated by the following procedure:

- Start with the natural numbers. Delete every 2nd number, leaving 1 3 5 7 9 11 13 15 17 19 21 23 ...
- the 2nd number remaining is 3, so delete every 3rd number, leaving 1 3 7 9 13 15 19 21 ...
- the 3rd number remaining is 7, so delete every 7th number, leaving 1 3 7 9 13 15 21 ...
- the 4th number remaining is 9, so delete every 9th number
- ... etc.

The first 10 lucky numbers are:
  1, 3, 7, 9, 13, 15, 21, 25, 31, 33, ...

Write a generator function that lazily produces all the lucky numbers.
 
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @jmoseley, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
