### ISSUE TITLE
Take Right with n elements from Array or String

### ISSUE THREAD

**Issue by shingz96** [rgehan/hacktoberfest-2k18-katas#1034]
# [takeRight]

### Link to the PR that adds this test case:

#1035

### Where to implement:

`src/takeRight.js`

### Where are the tests:

`src/takeRight.test.js`

### Description (optional):

Returns an array/string with n elements removed from the end while still keep the order. Default take 1 if no provide any number to take.
* EG 1: takeRight( [1,2,3,4,5,6], 5 ) -> [2,3,4,5,6]  
* EG 2: takeRight( "HACK", 3 ) -> "ACK" 

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/takeRight.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by mShreyasKumar** [comment]
/request: May I take on this issue

**Comment by rgehan** [comment]
Hey @mShreyasKumar, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by mphan6** [comment]
uhmmm okay.

**Comment by mShreyasKumar** [comment]
Unable to push code, not sure what is wrong
![image](https://user-images.githubusercontent.com/15031868/47454786-b5ac7780-d7ed-11e8-9a60-6a1aff0f513e.png)

**Comment by rgehan** [comment]
You're supposed to fork the repo, because I cannot allow anyone to push whatever they want

**Comment by rgehan** [comment]
Hey @mShreyasKumar,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @yavrib, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
