### ISSUE TITLE
humanReadableDuration

### ISSUE THREAD

**Issue by wallchuck** [rgehan/hacktoberfest-2k18-katas#1037]
# humanReadableDuration

### Link to the PR that adds this test case:

#1036

### Where to implement:

`src/humanReadableDuration.js`

### Where are the tests:

`src/humanReadableDuration.test.js`

### Description (optional):

 Write a function that accepts a non-negative integer,
 interprets it as a number of seconds and returns the duration
 in a human-readable format.

 Units in the returned value should be (in order):
 "years", "days", "hours", "minutes" and "seconds"

 Return "now" for input equal to 0.

 Separate units with a comma and a space (", ") except for the last unit,
 which should be separated with " and " - check out the test cases for examples.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @mphan6, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.
