### ISSUE TITLE
Implement covariance

### ISSUE THREAD

**Issue by nip10** [rgehan/hacktoberfest-2k18-katas#1040]
# covariance

### Link to the PR that adds this test case:

[the url]

### Where to implement:

`src/covariance.js`

### Where are the tests:

`src/covariance.test.js`

### Description (optional):

In probability theory and statistics, covariance is a measure of the joint variability of two random variables. ([source](https://en.wikipedia.org/wiki/Covariance))

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by NitinSingh2020** [comment]
@nip10 @rgehan I created https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1075 but had to update one test-case as I found fit. I have not completed the check list as I wait for your response here. Thanks.

**Comment by NitinSingh2020** [comment]
Thanks @nip10 ; I updated checklist at https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1075 to the best of my understanding. @rgehan please review.
