### ISSUE TITLE
Implement `isOdd`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#105]
### isOdd

**Link to the PR that adds this test case**: #91 
**Where to implement**: `src/isOdd.js`
**Where are the tests**: `src/isOdd.test.js`

Thanks :heart:

**Comment by t04glovern** [comment]
Working on it now :)

**Comment by 2wce** [comment]
On it

**Comment by iflare3g** [comment]
On it
