### ISSUE TITLE
Candy

### ISSUE THREAD

**Issue by sautumn** [rgehan/hacktoberfest-2k18-katas#1080]
# candy.js

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1079

### Where to implement:

`src/candy.js`

### Where are the tests:

`src/candy.test.js`

### Description (optional):

There are N children standing in a line. Each child is assigned a rating value.

You are giving candies to these children subjected to the following requirements:

Each child must have at least one candy.
Children with a higher rating get more candies than their neighbors.
What is the minimum candies you must give?

```
Example 1:
Input: [1,0,2]
Output: 5
Explanation: You can allocate to the first, second and third child with 2, 1, 2 
candies respectively.
```

```
Example 2:
Input: [1,2,2]
Output: 4
Explanation: You can allocate to the first, second and third child with 1, 2, 1 
candies respectively. The third child gets 1 candy because it satisfies the 
above two conditions.
```
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @benfes, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.
