### ISSUE TITLE
parenthesisMatcher

### ISSUE THREAD

**Issue by flagoon** [rgehan/hacktoberfest-2k18-katas#1087]
# [parenthesisMatcher]

### Link to the PR that adds this test case:

[/pull/845]

### Where to implement:

`src/paranthesisMatcher.js`

### Where are the tests:

`src/src/paranthesisMatcher.test.js`

### Description (optional):

The function accepts a string of opening and closing parenthesis. It returns the place in this string, where the number of open parentheses is equal of the number of the closed parenthesis.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @kylejlin, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
