### ISSUE TITLE
Implement `isPrime`

### ISSUE THREAD

**Issue by cptjacky** [rgehan/hacktoberfest-2k18-katas#109]
### isPrime

**Link to the PR that adds this test case**: #107
**Where to implement**: `src/isPrime.js`
**Where are the tests**: `src/isPrime.test.js`

Thanks :heart:

**Comment by ChintuYadav** [comment]
I will work on it

**Comment by ChintuYadav** [comment]
@rgehan Done with this! https://github.com/rgehan/hacktoberfest-2k18-katas/pull/113
