### ISSUE TITLE
Implement `encodeToCaesar`

### ISSUE THREAD

**Issue by Tassion** [rgehan/hacktoberfest-2k18-katas#112]
### encodeToCaesar

**Link to the PR that adds this test case**: #108 
**Where to implement**: `src/encodeToCaesar.js`
**Where are the tests**: `src/encodeToCaesar.test.js`
**Description**:
Using the Caesar cipher, your function take a string (to encode) and a shift. Must return the encoded string.

Thanks :heart:

**Comment by moogacs** [comment]
@rgehan  I could do this

**Comment by rgehan** [comment]
Go ahead

**Comment by moogacs** [comment]
@rgehan  , there's outside of /src encodeToCaesar , i think i have to remove it

**Comment by Tassion** [comment]
I failed my 1st PR commit, you can remove encodeToCeasar files that aren't in src/ !
