### ISSUE TITLE
Implement `sortNames`

### ISSUE THREAD

**Issue by t04glovern** [rgehan/hacktoberfest-2k18-katas#115]
# sortNames

### Link to the PR that adds this test case:
[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/114](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/114)

### Where to implement:
`src/sortNames.js`

### Where are the tests:
`src/sortNames.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by linosorice** [comment]
I'm on it

**Comment by rgehan** [comment]
Go ahead

**Comment by kumaran-14** [comment]
can i do this?

**Comment by cptjacky** [comment]
@kumaran-14 Please check the labels before asking. This one has the "assigned" label and is therefore not up for grabs.

**Comment by kumaran-14** [comment]
Okay sorry, but they have been inactive for sometime right?

**Comment by cptjacky** [comment]
We release the inactive ones from time to time, so just keep watching for an "up for grabs" one where no one already asked!

**Comment by rgehan** [comment]
Reopened as it seems to be stale.

**Comment by whathejoe** [comment]
Hi, I'd like to work on this

**Comment by rgehan** [comment]
@linosorice Are you working on it or shall I release it?

**Comment by linosorice** [comment]
Release it

**Comment by linosorice** [comment]
You can release it

**Comment by bereninga** [comment]
I'll take this one if it's still free.

**Comment by rgehan** [comment]
Yeah go ahead
assign: @bereninga

**Comment by rgehan** [comment]
Yeah go ahead
/assign @bereninga
