### ISSUE TITLE
Implement `convertIntToLetter`

### ISSUE THREAD

**Issue by TimothePearce** [rgehan/hacktoberfest-2k18-katas#12]

**Comment by TimothePearce** [comment]
@dimGlyn this time ?

**Comment by Dikaeinstein** [comment]
@rgehan has this being assigned? I'd like to work on it

**Comment by dimGlyn** [comment]
Heyyyyy yeah I' m here

**Comment by TimothePearce** [comment]
@Dikaeinstein sorry that's for @dimGlyn I stole his last issue, next one is for you 👍
