### ISSUE TITLE
Implement `decimalToHex`

### ISSUE THREAD

**Issue by shotozuro** [rgehan/hacktoberfest-2k18-katas#120]
# [decimalToHex]

### Link to the PR that adds this test case:
[PR #119 ](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/119)

### Where to implement:
`src/decimalToHex.js`

### Where are the tests:
`src/decimalToHex.test.js`

### Description (optional):
Simple converter from decimal to hexadecimal number
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by honmanyau** [comment]
I'll work on this one! :)

**Comment by rgehan** [comment]
The PR that added this issue was closed, you should wait for it to be resubmitted

**Comment by honmanyau** [comment]
No worries and thank you very much for letting me know! I haven't actually touched anything yet because the PR wasn't accepted earlier. Thanks for organising this by the way!
