### ISSUE TITLE
Implement `pow`

### ISSUE THREAD

**Issue by Sergeytroinin** [rgehan/hacktoberfest-2k18-katas#123]
# [Pow]

### Link to the PR that adds this test case:
#122 

### Where to implement:
`src/pow.js`

### Where are the tests:
`src/pow.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by vishal-wadhwa** [comment]
I'd like to take this one. :)

**Comment by lukebrobbs** [comment]
Ill do this

**Comment by rgehan** [comment]
Go ahead

**Comment by ChintuYadav** [comment]
@rgehan Is this still Open?

**Comment by rgehan** [comment]
No, read above
