### ISSUE TITLE
implement `isCorrectBracketSequence`

### ISSUE THREAD

**Issue by fritzlolpro** [rgehan/hacktoberfest-2k18-katas#124]
# isCorrectBracketSequence

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/88

### Where to implement:
`src/isCorrectBracketSequence.js`

### Where are the tests:
`src/isCorrectBracketSequence.test.js`

### Description (optional):
Classic kata

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by andrey-semin** [comment]
I'll take this

**Comment by rgehan** [comment]
Go ahead
