### ISSUE TITLE
Implement `sort`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#125]
# sort

### Link to the PR that adds this test case:
#70 

### Where to implement:
`src/sort.js`

### Where are the tests:
`src/sort.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by takethefake** [comment]
will do!

**Comment by moogacs** [comment]
still open or @takethefake  has taken it ? @rgehan

**Comment by rgehan** [comment]
I think @takethefake is on it, I'll tag it as "assigned"
