### ISSUE TITLE
Implement `arrayDifference`

### ISSUE THREAD

**Issue by andrey-semin** [rgehan/hacktoberfest-2k18-katas#127]
# arrayDifference

### Link to the PR that adds this test case:
#126 

### Where to implement:
`src/arrayDifference.js`

### Where are the tests:
`src/arrayDifference.test.js`

### Description (optional):
If the function is complex enough to warrant a description, add it here...

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by ye-lin-aung** [comment]
Done here is PR link - https://github.com/rgehan/hacktoberfest-2k18-katas/pull/130
