### ISSUE TITLE
Implement isEmail

### ISSUE THREAD

**Issue by ChintuYadav** [rgehan/hacktoberfest-2k18-katas#129]
# isEmail

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/128

### Where to implement:
`src/isEmail.js`

### Where are the tests:
`src/isEmail.test.js`

### Description (optional):
Check if a given string is Email or not?

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by moogacs** [comment]
i will take it

**Comment by Joaflora** [comment]
hey, can I work on it?
