### ISSUE TITLE
Implement `swapCase`

### ISSUE THREAD

**Issue by andrey-semin** [rgehan/hacktoberfest-2k18-katas#132]
# swapCase

### Link to the PR that adds this test case:
#131 

### Where to implement:
`src/swapCase.js`

### Where are the tests:
`src/swapCase.test.js`

### Description (optional):
Write a function that returns the string `str` with inverted case per character (stR -> STr)
Numeric and special characters shall be ignored

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Zaksh** [comment]
I would like to work on this.

**Comment by cptjacky** [comment]
Go ahead @Zaksh, it's yours!
