### ISSUE TITLE
Implement Pillars 

### ISSUE THREAD

**Issue by takethefake** [rgehan/hacktoberfest-2k18-katas#133]
# Pillars

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/141

### Where to implement:
`src/pillars.js`

### Where are the tests:
`src/pillars.test.js`

### Description
There are pillars near the road. The distance between the pillars is the same
and the width of the pillars is the same. Your function accepts three arguments:

 - number of pillars (≥ 1);
 - distance between pillars (10 - 30 meters);
 - width of the column (10 - 50 centimeters).

 Calculate the distance between the first and the last pillar
 in centimeters (without the width of the first and last pillar).

---

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by ofaltins** [comment]
I'd like to tackle this one!

**Comment by cptjacky** [comment]
Go ahead, it's all yours @ofaltins 👍
