### ISSUE TITLE
implement countSheep.js

### ISSUE THREAD

**Issue by lukebrobbs** [rgehan/hacktoberfest-2k18-katas#135]
# countSheep

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/134

### Where to implement:
`src/countSheep.js`

### Where are the tests:
`src/countSheep.test.js`

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by carolinajimenez26** [comment]
can I work on it?

**Comment by gtl90** [comment]
I will work on this please assign me this issue.

**Comment by cptjacky** [comment]
It's all yours @gtl90 :)

**Comment by rgehan** [comment]
Reopened as it seems to be stale.

**Comment by pynnl** [comment]
I'd like to take this if possible. Thank you.

**Comment by s22su** [comment]
Can I get it, please?
