### ISSUE TITLE
Implement BasicMath

### ISSUE THREAD

**Issue by takethefake** [rgehan/hacktoberfest-2k18-katas#139]
# Basic Math

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/141

### Where to implement:
`src/basicMath.js`

### Where are the tests:
`src/basicMath.test.js`

### Description (optional):
Your task is to create a function that does four basic mathematical operations.

The function should take three arguments - operation(string/char), value1(number), value2(number).
The function should return result of numbers after applying the chosen operation.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by carolinajimenez26** [comment]
Can I work on it?

**Comment by cptjacky** [comment]
It's all yours @carolinajimenez26 👍

**Comment by carolinajimenez26** [comment]
There was a problem in the `src/basicMath.test.js`, it was missing a `(` and `)` in the `expect `
