### ISSUE TITLE
Implement Product

### ISSUE THREAD

**Issue by 2wce** [rgehan/hacktoberfest-2k18-katas#140]
# Product

### Link to the PR that adds this test case:
*https://github.com/rgehan/hacktoberfest-2k18-katas/pull/137*

### Where to implement:
`src/product.js`

### Where are the tests:
`src/product.test.js`

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by carolinajimenez26** [comment]
There is not `src/product.js` file

**Comment by Joaflora** [comment]
Can I work on it? :)

**Comment by rgehan** [comment]
Yep

**Comment by Joaflora** [comment]
What should I do?

**Comment by rgehan** [comment]
I don't know, work on it maybe? :p

Just read the README, there are instructions

**Comment by lourdesr** [comment]
Next in line, if that's okay.

**Comment by lourdesr** [comment]
Hey @rgehan - I'm ready with my PR.
