### ISSUE TITLE
Implement Opposite Numbers

### ISSUE THREAD

**Issue by ye-lin-aung** [rgehan/hacktoberfest-2k18-katas#143]
# Opposite Numbers

### Link to the PR that adds this test case:
[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/142]

### Where to implement:
`src/opposite.js`

### Where are the tests:
`src/opposite.test.js`

### Description (optional):
Very simple, given a number, find its opposite.

Examples:
```
if input is 1 the opposite of it is -1
and 14 is  -14
and -34 is 34
```

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
- A fixed implementation of the function
- A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by 142ayushkumar** [comment]
Can you assign this issue to me?

**Comment by cptjacky** [comment]
Alright, it's yours @142ayushkumar 👍

**Comment by KumarManoj-S** [comment]
I would like to take this!
