### ISSUE TITLE
Implement isLink

### ISSUE THREAD

**Issue by moogacs** [rgehan/hacktoberfest-2k18-katas#144]
# isLink

### Link to the PR that adds this test case:
[[129](https://github.com/rgehan/hacktoberfest-2k18-katas/issues/129)]

### Where to implement:
`src/isLink.js`

### Where are the tests:
`src/isLink.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by grv19** [comment]
I'll take this one.

**Comment by cptjacky** [comment]
Alright @grv19 it's yours 👍
