### ISSUE TITLE
Implement `decimalToHex`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#145]
# decimalToHex

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/138/files

### Where to implement:
`src/decimalToHex.js`

### Where are the tests:
`src/decimalToHex.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by mikek2** [comment]
I'll take this one!

**Comment by cptjacky** [comment]
Alright, it's yours @mikek2 👍

**Comment by rgehan** [comment]
Reopened as it seems to be stale.

**Comment by mikek2** [comment]
Sorry for the delay, I will post a PR tonight when I get home from work!

**Comment by rgehan** [comment]
No problem, I'm cleaning up a bit as we have quite a lot of stale issues. I'll reassign it to you
