### ISSUE TITLE
Implement isPowerOfTwo

### ISSUE THREAD

**Issue by 142ayushkumar** [rgehan/hacktoberfest-2k18-katas#148]
# [IsPowerOfTwo]

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/147

### Where to implement:
`src/isPowerOfTwo.js`

### Where are the tests:
`src/isPowerOfTwo.test.js`

### Description (optional):
You have to return true if passed number is a power of two otherwise return false
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by kumaran-14** [comment]
I ll take this

**Comment by cptjacky** [comment]
PR was just merged, just pull the repo again and the test files will be here :) 
That one is yours @kumaran-14
