### ISSUE TITLE
Implement isValidIP for IPv4 and IPv6 Addresses

### ISSUE THREAD

**Issue by grv19** [rgehan/hacktoberfest-2k18-katas#150]
# isValidIP

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/149

### Where to implement:
`src/isValidIP.js`

### Where are the tests:
`src/isValidIP.test.js`

### Description (optional):
If the function is complex enough to warrant a description, add it here...

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by mrkidsan** [comment]
May I take this?

**Comment by KumarManoj-S** [comment]
can i take this?

**Comment by rgehan** [comment]
@mrkidsan Go ahead

**Comment by rgehan** [comment]
Reopened as it seems to be stale.
