### ISSUE TITLE
Implement `countingPrimes`

### ISSUE THREAD

**Issue by cptjacky** [rgehan/hacktoberfest-2k18-katas#151]
# countingPrimes

### Link to the PR that adds this test case:
#146 

### Where to implement:
`src/countingPrimes.js`

### Where are the tests:
`src/countingPrimes.test.js`

### Description (optional):
If the function is complex enough to warrant a description, add it here...

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by 142ayushkumar** [comment]
can you assign this issue to me?

**Comment by KumarManoj-S** [comment]
Can I take this?

**Comment by SLR1999** [comment]
I am interested in this issue. Can I do it?
Is it necessary to implement only in js?

**Comment by rgehan** [comment]
@142ayushkumar Go ahead

**Comment by 142ayushkumar** [comment]
@rgehan i am getting this error when i test my code
![image](https://user-images.githubusercontent.com/23264605/46426299-c4a68980-c75b-11e8-9189-bf588cb3279f.png)
Any idea what is going wrong?

**Comment by rgehan** [comment]
Maybe `cd ..` into the main directory?

**Comment by 142ayushkumar** [comment]
@rgehan there is some mistake in countingPrimes.test.js , please check
