### ISSUE TITLE
Implement 'removeValue'

### ISSUE THREAD

**Issue by gattigaga** [rgehan/hacktoberfest-2k18-katas#152]
# removeValue

### Link to the PR that adds this test case:
#58 

### Where to implement:
`src/removeValue.js`

### Where are the tests:
`src/removeValue.test.js`

### Description (optional):
Function should returns a new array without values which are removed.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by KumarManoj-S** [comment]
can I take this?

**Comment by rgehan** [comment]
@suzicurran Do you still want it?

**Comment by suzicurran** [comment]
Yep, sorry, got pulled away with work! Thanks for checking.
