### ISSUE TITLE
Implement countCodeLines

### ISSUE THREAD

**Issue by ofaltins** [rgehan/hacktoberfest-2k18-katas#157]
# countCodeLines

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/156

### Where to implement:
`src/countCodeLines.js`

### Where are the tests:
`src/countCodeLines.test.js`

### Description (optional):
Write a utility that counts the number of lines of actual code in a javascript source string, excluding comments and whitespace. The function accepts a multiline string, and returns an integer

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by KumarManoj-S** [comment]
Can I take this?

**Comment by rgehan** [comment]
There is no point asking after someone JUST asked, we'll ALWAYS give it to the first person who asked for it

**Comment by rgehan** [comment]
@kumaran-14 You go ahead

**Comment by kumaran-14** [comment]
I'm a bit busy, can you assign someone else to this?

**Comment by rgehan** [comment]
@mannutech Go ahead
