### ISSUE TITLE
Implement `factorial`

### ISSUE THREAD

**Issue by cptjacky** [rgehan/hacktoberfest-2k18-katas#16]

**Comment by rbo13** [comment]
Hi @cptjacky, can I take this one? Or someone is already implementing this?

**Comment by rgehan** [comment]
Yes you can !

**Comment by rbo13** [comment]
Thanks @rgehan

**Comment by rbo13** [comment]
Hi @rgehan CC @cptjacky, already created a PR that supports `factorial` 👍 kindly check it

**Comment by srsandy** [comment]
i can slove this.

**Comment by rgehan** [comment]
@srsandy Yes go ahead

**Comment by srsandy** [comment]
#87 Done 👍

**Comment by rgehan** [comment]
Released as the PR doesn't follow the rules

**Comment by ChintuYadav** [comment]
@rgehan Shall I work on it?

**Comment by rgehan** [comment]
Yes go ahead
