### ISSUE TITLE
Convert C to F

### ISSUE THREAD

**Issue by lourdesr** [rgehan/hacktoberfest-2k18-katas#160]
# cToF
### Link to the PR that adds this test case:
[#159](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/159)

### Where to implement:
`src/cToF.js`

### Where are the tests:
`src/cToF.test.js`

### Description (optional):
Converts Celcius to Farenheit (Formula given in test case)

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by KumarManoj-S** [comment]
Can I take this?

**Comment by rgehan** [comment]
Finally @KumarManoj-S, you're the first on the issue ! :)

Yes, take it!

**Comment by kumaran-14** [comment]
Can i do this? as no response came from @KumarManoj-S ?

**Comment by rgehan** [comment]
While I can understand your excitement, it's only been two hours.

Stop spamming and wait for your turn

**Comment by rgehan** [comment]
Reopened as it seems to be stale.

**Comment by xingwang** [comment]
I'll take it

**Comment by rgehan** [comment]
Go ahead
