### ISSUE TITLE
Implement 'primeFactors'

### ISSUE THREAD

**Issue by kumaran-14** [rgehan/hacktoberfest-2k18-katas#161]
# primeFactors

### Link to the PR that adds this test case:
*https://github.com/rgehan/hacktoberfest-2k18-katas/pull/158*

### Where to implement:
`src/primeFactors.js`

### Where are the tests:
`src/primeFactors.test.js`

### Description (optional):
Simple enough, just go through the tests

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by lourdesr** [comment]
I'm taking it!

**Comment by KumarManoj-S** [comment]
Can I take this?

**Comment by rgehan** [comment]
Go ahead @lourdesr

**Comment by lourdesr** [comment]
Hey @rgehan - I'm on it. The test cases have _'toBeEqual'_, when I run 'yarn test' it asks me to change it to _'toEqual'_.

Can I change it in the test case: `src/primeFactors.test.js`

**Comment by rgehan** [comment]
Yeah go ahead, if there's an error in the test it's ok

**Comment by lourdesr** [comment]
Cool, will send a PR soon.
