### ISSUE TITLE
Implement sumOfPairs

### ISSUE THREAD

**Issue by 0c0de** [rgehan/hacktoberfest-2k18-katas#163]
# sumOfPairs

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/162

### Where to implement:
`src/sumOfPairs.js`

### Where are the tests:
`src/sumOfPairs.test.js`

### Description (optional):
Very simple :smile:  sum the pairs of a numbers in a range like from 0 to 6

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Go ahead @torendo

**Comment by rgehan** [comment]
@torendo Do you still want it?

**Comment by sivcan** [comment]
@rgehan If it's open for reassignment, I can take this up.

**Comment by torendo** [comment]
@rgehan, good morning! You just forgot about time zones =) If it possible, I still want to do it

**Comment by rgehan** [comment]
I'm not forgetting timezones, but we have so many people asking for a chance to take the issues that it's difficult to decide what to do when we see an issue/PR that was inactive for 9h.

I'll gladly reassign it to you

**Comment by torendo** [comment]
Oh, understood. Thank you for your time, by the way.

**Comment by torendo** [comment]
@rgehan I've finished. It's my first PR on GitHub ever.
Also in tests was one with a bug: 
`  it('goes from 5 to 15', () => {
    expect(sumOfPairs([5,15])).toEqual(50);
  });`
result from 5 to 15 should be equals to 60, because of sequence: 5 7 9 11 13 15

**Comment by rgehan** [comment]
@torendo Shouldn't it be the "sum of pair numbers between 5 to 15"?
In that case, I think it would be `6 8 10 12 14`

**Comment by torendo** [comment]
@rgehan I've just did a fix. Thanks for your patience =)
