### ISSUE TITLE
Implement 'largestString'

### ISSUE THREAD

**Issue by lourdesr** [rgehan/hacktoberfest-2k18-katas#166]
# largestString

### Link to the PR that adds this test case:
[#165](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/165)

### Where to implement:
`src/largestString.js`

### Where are the tests:
`src/largestString.test.js`

### Description (optional):
Just return all the largest string from the given list of string. Quite easy, check out the test cases.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by vishal-wadhwa** [comment]
Hi!

Can I take this one?

**Comment by 00aney** [comment]
Can I take it?

**Comment by rgehan** [comment]
Yep

**Comment by rgehan** [comment]
@00aney Do you still want it?
