### ISSUE TITLE
Implement gcd

### ISSUE THREAD

**Issue by 142ayushkumar** [rgehan/hacktoberfest-2k18-katas#170]
# gcd

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/169

### Where to implement:
`src/gcd.js`

### Where are the tests:
`src/gcd.test.js`

### Description (optional):
Just return Greatest Common Divisor
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by 142ayushkumar** [comment]
can you assign me this issue?

**Comment by rgehan** [comment]
You created it, we'll leave it to someone else

**Comment by lchaglla** [comment]
il take it

**Comment by mannutech** [comment]
I am also in to take this.

**Comment by rgehan** [comment]
@lchaglla Go ahead

**Comment by mannutech** [comment]
@rgehan Can you create a request to do Bignumber handling and I will take care of this.

**Comment by 142ayushkumar** [comment]
@rgehan I think creating few more problems will be better idea, because many people here want to contribute. What about sending a PR with few problems ?
