### ISSUE TITLE
Implement sieveOfEratosthenes

### ISSUE THREAD

**Issue by honeyyenoh** [rgehan/hacktoberfest-2k18-katas#173]
# cToF
### Link to the PR that adds this test case:
[#159](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/171)

### Where to implement:
`src/sieveOfEratosthenes.js`

### Where are the tests:
`src/sieveOfEratosthenes.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by kumaran-14** [comment]
i ll do this

**Comment by rgehan** [comment]
Ok go ahead
