### ISSUE TITLE
Implement `addKeyAndValueToObject`

### ISSUE THREAD

**Issue by piksu** [rgehan/hacktoberfest-2k18-katas#174]
# addKeyAndValueToObject

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/96

### Where to implement:
`src/addKeyAndValueToObject.js`

### Where are the tests:
`src/addKeyAndValueToObject.test.js`

### Description (optional):
```js
let input = {};
let output = addKeyAndValueToObject(input, "myKey", "myValue");
// Value of output should now be: {myKey: "myValue"}
```

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by honeyyenoh** [comment]
can i take this issue?

**Comment by rgehan** [comment]
Yes go ahead @honeyyenoh
