### ISSUE TITLE
Implement `tokenizer`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#175]
# tokenizer

:warning: This one might be a bit difficult/time-consuming :warning:

### Where to implement:
`src/tokenizer.js`

### Where are the tests:
`src/tokenizer.test.js`

### Description (optional):
This is the first step towards implementing an interpreter. "Tokenization" simply means transforming a sequence of characters into a sequence of tokens. This tokens are then fed into another step of the compiler/interpreter: the parser.

What I'm proposing you today, is to implement that first step by yourself (it's fun I promise).

References:
- http://www.craftinginterpreters.com/contents.html
- https://en.wikipedia.org/wiki/Lexical_analysis#Tokenization

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Zaksh** [comment]
Can I take it ?

**Comment by rgehan** [comment]
You totally can, but this could take you a long time.

Do you still want it?

**Comment by Zaksh** [comment]
I just checked the test case and for now I can see the test case include

- const
- identifier
- numbers
- operators
- semicolon

Do you intend to add some more tokens or that's all ?

**Comment by rgehan** [comment]
No that's all, we could do much more, but this is enough for a kata

**Comment by yurrr** [comment]
In case @Zaksh doesn't . I'd like to do this.

**Comment by Zaksh** [comment]
@rgehan Yes, I will do it.

**Comment by rgehan** [comment]
Ok @Zaksh, it's for you

**Comment by rgehan** [comment]
@Zaksh Are you working on it or shall I release it?

**Comment by Zaksh** [comment]
@rgehan I haven't started working yet as I am reading the articles you shared. Also, I am not working full time on this so it may take some time. If you want it early, you may assign it to someone (I don't have any issue with that) as it may take some time on my end but I am working on this steady and slowly :)

**Comment by rgehan** [comment]
That's ok if you take some time, just wanted to know if you were on it :)

**Comment by vishal-wadhwa** [comment]
I've not been assigned this issue but had a little doubt.

@rgehan The first two test cases have lexeme as '10' for numbers 20 and 5. Are you sure it's that way?

Thanks

**Comment by rgehan** [comment]
@vishal-wadhwa You're right, fixed it in ce6e3db

**Comment by rgehan** [comment]
Hey @Zaksh,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @AliNisarAhmed, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by AliNisarAhmed** [comment]
ok no problem, i will request for another one.

**Comment by AliNisarAhmed** [comment]
Please un-assign from me so I can work on some other problem.

**Comment by rgehan** [comment]
Pinging @Zaksh so that the bot doesn't reset the issue

**Comment by rgehan** [comment]
Hey @Zaksh,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by Zaksh** [comment]
Ping @rgehan so that the bot doesn't reset the issue

**Comment by rgehan** [comment]
Hey @Zaksh,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by chrisza4** [comment]
Can I take it?

**Comment by yurrr** [comment]
I had asked for It before , can i  take It ?
/request

**Comment by rgehan** [comment]
Hey @yurrr, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey sorry @yurr, this one is a bit time consuming and should not be reset.

It's still for @Zaksh until tomorrow, after that, I'll really release it

/assign @Zaksh

**Comment by rgehan** [comment]
I've modified the auto release bot so that it ignores issues with the `no auto reset` label.

You're safe for now :)
