### ISSUE TITLE
Implement integerToRoman

### ISSUE THREAD

**Issue by lchaglla** [rgehan/hacktoberfest-2k18-katas#178]
# integerToRoman

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/177

### Where to implement:
`src/integerToRoman.js`

### Where are the tests:
`src/integerToRoman.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Delkhaz** [comment]
ill take care of this

**Comment by rgehan** [comment]
Go ahead

**Comment by Delkhaz** [comment]
will complete tonight, please dont reassign
