### ISSUE TITLE
Implement 'firstRecurringChar'

### ISSUE THREAD

**Issue by kumaran-14** [rgehan/hacktoberfest-2k18-katas#184]
# firstRecurringChar
### Link to the PR that adds this test case:
*https://github.com/rgehan/hacktoberfest-2k18-katas/pull/182*

### Where to implement:
`src/firstRecurringChar.js`

### Where are the tests:
`src/firstRecurringChar.test.js`

### Description (optional):
Not to complex, check the test cases.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by honeyyenoh** [comment]
can I take?

**Comment by rgehan** [comment]
@honeyyenoh Yep
