### ISSUE TITLE
Implement replaceChars

### ISSUE THREAD

**Issue by honeyyenoh** [rgehan/hacktoberfest-2k18-katas#187]
# replaceChars

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/185

### Where to implement:
`src/replaceChars.js`

### Where are the tests:
`src/replaceChars.test.js`

### Description (optional):
If the function is complex enough to warrant a description, add it here...

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by igorantun** [comment]
I can take this

**Comment by rgehan** [comment]
How do you manage to use the PR template each time 😛

**Comment by AntonStrand** [comment]
If this is an actual issue I would be interested

**Comment by rgehan** [comment]
Take it :)

**Comment by honeyyenoh** [comment]
@rgehan it's magic! My last one has an usual template :)
