### ISSUE TITLE
Implement romanToInteger

### ISSUE THREAD

**Issue by lchaglla** [rgehan/hacktoberfest-2k18-katas#188]
# romanToInteger

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/186

### Where to implement:
`src/romanToInteger.js`

### Where are the tests:
`src/romanToInteger.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by mannutech** [comment]
I will take

**Comment by rgehan** [comment]
Go ahead @mannutech

**Comment by rgehan** [comment]
@mannutech Are you working on it or shall I release it?

**Comment by mannutech** [comment]
@rgehan I am continuing on this.
