### ISSUE TITLE
Implement findAngleByClock

### ISSUE THREAD

**Issue by honeyyenoh** [rgehan/hacktoberfest-2k18-katas#194]
# findAngleByClock

### Link to the PR that adds this test case:
[#193](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/193)

### Where to implement:
`src/findAngleByClock.js`

### Where are the tests:
`src/findAngleByClock.test.js`

### Description (optional):
Find an angle between hours and minutes hands

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by sajadhsm** [comment]
I take it :)

**Comment by rgehan** [comment]
Ok 👍
