### ISSUE TITLE
Implement wordSpiral

### ISSUE THREAD

**Issue by Oshawk** [rgehan/hacktoberfest-2k18-katas#195]
# wordSpiral

:warning: This one is potentially more challenging than the others, so take it if you have a bit of time ahead of you :warning:

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/192

### Where to implement:
`src/wordSpiral.js`

### Where are the tests:
`src/wordSpiral.test.js`

### Description:
You do not have a description of what it should do, all you have are the inputs and outputs. All inputs are strings and all outputs are required to be arrays of strings.

#### Example 1:

Input:
```text
abcdefghijklmnopqrstuvwxyz
```

Output:
```js
[
'xxxxxxxxxxxxxxxxxxxxxxxxw  ',
'y                       w  ',
'y tttttttttttttttttttts w  ',
'y u                   s w  ',
'y u ppppppppppppppppo s w  ',
'y u q               o s w  ',
'y u q llllllllllllk o s w  ',
'y u q m           k o s w  ',
'y u q m hhhhhhhhg k o s w  ',
'y u q m i       g k o s w  ',
'y u q m i ddddc g k o s w  ',
'y u q m i e   c g k o s w  ',
'y u q m i e   c g k o s w  ',
'y u q m i e abb g k o s w  ',
'y u q m i e     g k o s w  ',
'y u q m i effffff k o s w  ',
'y u q m i         k o s w  ',
'y u q m ijjjjjjjjjj o s w  ',
'y u q m             o s w  ',
'y u q mnnnnnnnnnnnnnn s w  ',
'y u q                 s w  ',
'y u qrrrrrrrrrrrrrrrrrr w  ',
'y u                     w  ',
'y uvvvvvvvvvvvvvvvvvvvvvv  ',
'y                          ',
'yzzzzzzzzzzzzzzzzzzzzzzzzzz',
]
```

#### Example 2:

Input:
```text
adbbeb
```

Output:
```js
[
'  bbb',
'  e b',
'adedd',
'  e  ',
'  e  ',
'  ebb',
]
```

#### Example 3:

Input:
```text
wordspiral
```

Output:
```js
[
'w                           ',
'w                           ',
'w                           ',
'w                           ',
'w          ddddr            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w          s   r            ',
'w        rrrrrrrrrrrrrrrrrri',
'w        allllllllllll     i',
'w          s   r           i',
'w          s   r           i',
'w          s   r           i',
'w          s   r           i',
'w          s   r           i',
'w          s   r           i',
'woooooooooosoooo           i',
'           spppppppppppppppp',
]
```

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
@Oshawk Could you explain a bit where the spiral should start? From the two examples I find it a bit confusing

**Comment by Oshawk** [comment]
There is no real starting position, the spiral just grows from a point and is padded with spaces into the smallest possible box. This is a copy of a kata I made a while ago for Python (https://www.codewars.com/kata/word-spiral/python). Part of the game is to work out what is going on.

**Comment by rgehan** [comment]
So it's still deterministic? Because if it's not we're going to have a problem with that strict `Jest.toEqual` assertion 😛

**Comment by Oshawk** [comment]
Yep, absolutely, the alphabet example is the easiest to see what is going on. The other examples show what should happen in the case of overlaps. Don't really want to say too much more. It is certainly a fairly challenging one but 16 people got it over at codewars so is deff possible.

**Comment by rgehan** [comment]
Cool then! I added a small "warning" in the description so that it's not assigned to someone that will give up immediately

**Comment by pynnl** [comment]
Although i'm requesting for another issue, I've already done it, and also this word spiral seems to be interesting, can I work on this too, while waiting for the other issue to be assigned? Thank you.
