### ISSUE TITLE
Convert F to C

### ISSUE THREAD

**Issue by xingwang** [rgehan/hacktoberfest-2k18-katas#198]
# fToC

### Link to the PR that adds this test case:
#196 

### Where to implement:
`src/fToC.js`

### Where are the tests:
`src/fToC.js.test.js`

### Description (optional):
Converts Farenheit to Celcius (Formula given in test case). Throws an ValidationError if undefined is passed in.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by SGospodinov** [comment]
Can I take this one

**Comment by joaopjt** [comment]
Can i get this one? Will take only a few minutes

**Comment by rgehan** [comment]
Yep go ahead
