### ISSUE TITLE
Implement `mode`

### ISSUE THREAD

**Issue by AntonStrand** [rgehan/hacktoberfest-2k18-katas#199]
# mode

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/197

### Where to implement:
`src/mode.js`

### Where are the tests:
`src/mode.test.js`

### Description (optional):
Return an array of the most frequent numbers in the provided array.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by WrightKD** [comment]
Can I work on this ?

**Comment by rgehan** [comment]
Yes go ahead
