### ISSUE TITLE
Implement findAnagram

### ISSUE THREAD

**Issue by 00aney** [rgehan/hacktoberfest-2k18-katas#204]
# findAnagarm

### Link to the PR that adds this test case:
#203

### Where to implement:
`src/findAnagarm.js`

### Where are the tests:
`src/findAnagarm.test.js`

### Description (optional):
return anagram string array

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by pynnl** [comment]
Hi, I'm interested in this. Can I take it?

**Comment by rgehan** [comment]
Ok
