### ISSUE TITLE
Implement atbash

### ISSUE THREAD

**Issue by lucasheim** [rgehan/hacktoberfest-2k18-katas#209]
# atbash

### Link to the PR that adds this test case:
#208 

### Where to implement:
`src/atbash.js`

### Where are the tests:
`src/atbash.test.js`

### Description (optional):
The Atbash cipher is a very common, simple cipher. Basically, when encoded, an "A" becomes a "Z", "B" turns into "Y", "C" becomes "X", etc.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by suzicurran** [comment]
I'd like to take this once the PR is merged in, thanks!

**Comment by rgehan** [comment]
Go ahead
