### ISSUE TITLE
Implement `get`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#21]
### Get

**Where to implement**: `src/get.js`
**Where are the tests**: `src/get.test.js`
**Description**:
This function is a safe way of getting a value in a nested object/array

Thanks :heart:

**Comment by jorge-andre** [comment]
Hey, I would like to work on this

**Comment by rgehan** [comment]
Go ahead!

**Comment by TimothePearce** [comment]
@jorge-andre any PR ?

**Comment by kumaran-14** [comment]
i ll do this

**Comment by jorge-andre** [comment]
Got a little caught up, someone else can do it. My apologies
