### ISSUE TITLE
Implement Slug

### ISSUE THREAD

**Issue by VickyKoblinski** [rgehan/hacktoberfest-2k18-katas#213]
# Slug

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/212
### Where to implement:
`src/slug.js`

### Where are the tests:
`src/slug.test.js`

### Description (optional):
Slug takes a string, trims it, and then replaces all spaces ( ) with underscores (_).

Example: '   My string!' => 'My_string!'

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by whathejoe** [comment]
Hi, I'd like to take this please

**Comment by rgehan** [comment]
Go ahead

**Comment by whathejoe** [comment]
thanks. will send a PR later today
