### ISSUE TITLE
Implement isObject

### ISSUE THREAD

**Issue by suzicurran** [rgehan/hacktoberfest-2k18-katas#214]
# isObject

### Link to the PR that adds this test case:
[#215](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/215)

### Where to implement:
`src/isObject.js`

### Where are the tests:
`src/isObject.test.js`

### Description (optional):
Given an element, say if it's an object or not! Note that there are many sorts of objects. :)

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by kumaran-14** [comment]
I will take this

**Comment by rgehan** [comment]
You already have one, do not take them all for yourself

**Comment by viswanathamsantosh** [comment]
Can I work on this?

**Comment by rgehan** [comment]
Yes
