### ISSUE TITLE
implement `nthRoot`

### ISSUE THREAD

**Issue by Delkhaz** [rgehan/hacktoberfest-2k18-katas#217]
# nthRoot

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/218

### Where to implement:
`src/nthRoot.js`

### Where are the tests:
`src/nthRoot.test.js`

### Description (optional):
calculate the nth root of a give number

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by jrga03** [comment]
Hi, can I take this?

**Comment by rgehan** [comment]
Yes
