### ISSUE TITLE
Implement oddOccurrencesInArray

### ISSUE THREAD

**Issue by torendo** [rgehan/hacktoberfest-2k18-katas#228]
# oddOccurrencesInArray

### Link to the PR that adds this test case:
[#227](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/227)

### Where to implement:
`src/oddOccurrencesInArray.js`

### Where are the tests:
`src/oddOccurrencesInArray.test.js`

### Description (optional):
A non-empty array A consisting of integers is given. The array contains an odd number of elements, and each element of the array can be paired with another element that has the same value, except for one element that is left unpaired. Write a function that, returns the value of the unpaired element.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Yep go ahead

assign: @pynnl
