### ISSUE TITLE
Implement `omit`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#23]
### Omit

**Where to implement**: `src/omit.js`
**Where are the tests**: `src/omit.test.js`
**Description**:
It acts as `lodash.omit`, but please dont copy/paste it, it's not fun!

Thanks :heart:

**Comment by tatchi** [comment]
Hi,

Can i take this one? :)

**Comment by rgehan** [comment]
Yep go ahead!
