### ISSUE TITLE
Implement 'contains'

### ISSUE THREAD

**Issue by devcer** [rgehan/hacktoberfest-2k18-katas#230]
# contains

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/229

### Where to implement:
`src/contains.js`

### Where are the tests:
`src/contains.test.js`

### Description (optional):
contains should accept two parameters, an array, and a value. The function should check if the value is present in the array and return a boolean.
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by WrightKD** [comment]
Can I work on this ?

**Comment by sobelek** [comment]
Could you assign me here?

**Comment by rgehan** [comment]
Go ahead
