### ISSUE TITLE
Implement `isTruthy`

### ISSUE THREAD

**Issue by whathejoe** [rgehan/hacktoberfest-2k18-katas#235]
# isTruthy

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/231

### Where to implement:
`src/isTruthy.js`

### Where are the tests:
`src/isTruthy.test.js`

### Description (optional):
The function returns `true` for truthy values and `false` for falsy values.

```javascript
isTruthy(1);         // true
isTruthy('yes');     // true
isTruthy(true);      // true
isTruthy(0);         // false
isTruthy(false);     // false
isTruthy(null);      // false
isTruthy(undefined); // false
```

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by lemcz** [comment]
Please assign this one to me. Thanks :)

**Comment by rgehan** [comment]
Go ahead
