### ISSUE TITLE
Implement `findIndex` without Array.findIndex

### ISSUE THREAD

**Issue by joaopjt** [rgehan/hacktoberfest-2k18-katas#237]
# findIndex

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/236

### Where to implement:
`src/findIndex.js`

### Where are the tests:
`src/findIndex.test.js`

### Description (optional):
Returns the first index where the predicate truth test passes; otherwise returns -1.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by ivansieder** [comment]
would like to take it! :)

**Comment by hirenchauhan2** [comment]
Hi, can I take this one?

**Comment by joaopjt** [comment]
> Hi, can I take this one?

Hey, go ahead 😄

**Comment by jrga03** [comment]
Hi, is this assigned? Can I take this?

**Comment by hirenchauhan2** [comment]
@jrga03 this is taken care by me!
