### ISSUE TITLE
Implement toPigLatin

### ISSUE THREAD

**Issue by suzicurran** [rgehan/hacktoberfest-2k18-katas#238]
# toPigLatin

### Link to the PR that adds this test case:
[239](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/239)

### Where to implement:
`src/toPigLatin.js`

### Where are the tests:
`src/toPigLatin.test.js`

### Description (optional):
`toPigLatin` should take a string and transform it into Pig Latin. The tests should guide you through the necessary edge cases, but see https://en.wikipedia.org/wiki/Pig_Latin if you get stuck! :)

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Banb4n** [comment]
Can I take this?

**Comment by rgehan** [comment]
Go ahead
