### ISSUE TITLE
Implement `range`

### ISSUE THREAD

**Issue by rzgry** [rgehan/hacktoberfest-2k18-katas#240]
# range

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/241

### Where to implement:
`src/range.js`

### Where are the tests:
`src/range.test.js`

### Description (optional):

The range of a array of numbers is the difference between the smallest and largest values.
Ex. the range of [3, 7, 4, 2, 6] is [2, 7].

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by s22su** [comment]
I can deal with it, please assign it to me.

**Comment by rgehan** [comment]
Go ahead
