### ISSUE TITLE
Implement kthSmallest 

### ISSUE THREAD

**Issue by hirenchauhan2** [rgehan/hacktoberfest-2k18-katas#245]
# kthSmallest

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/244

### Where to implement:
`src/kthSmallest.js`

### Where are the tests:
`src/kthSmallest.test.js`

### Description (optional):
Given an array and a number k where k is smaller than the size of the array, we need to find the k’th smallest element in the given array. It is given that all array elements are distinct.
**Examples**:
```js
kthSmallest([7, 10, 4, 3, 20, 15], 3);  // should return  7
kthSmallest([7, 10, 4, 3, 20, 15], 4);  // should return 10
```
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by sadarshannaiynar** [comment]
Can I take this?

**Comment by hirenchauhan2** [comment]
@sadarshannaiynar go ahead! 👍
