### ISSUE TITLE
Implement reverseArray

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#248]
# reverseArray

### Link to the PR that adds this test case:
#234 

### Where to implement:
`src/reverseArray.js`

### Where are the tests:
`src/reverseArray.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by assertnotnull** [comment]
I want to take it

**Comment by rgehan** [comment]
Go ahead
