### ISSUE TITLE
Implement findLastItem

### ISSUE THREAD

**Issue by Banb4n** [rgehan/hacktoberfest-2k18-katas#250]
# findLastItem

### Link to the PR that adds this test case:
#249 

### Where to implement:
`src/findLastItem.js`

### Where are the tests:
`src/findLastItem.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by bhagatparwinder** [comment]
I can do this. Please assign.

Quick note, in the test

`{
    value: 'hello',
    expected: 'h'
  }`

should be

`{
    value: 'hello',
    expected: 'o'
  }`

right?

**Comment by KumarManoj-S** [comment]
Can I take this ?

**Comment by rgehan** [comment]
If there is an error, fix it in your PR, the Travis tests will ultimately fine but I'll still merge it.

/assign @bhagatparwinder

**Comment by bhagatparwinder** [comment]
Sounds good. Thanks @rgehan

**Comment by rgehan** [comment]
Hey @bhagatparwinder,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @Yatheesan, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by bhagatparwinder** [comment]
I can't resist but shake my head. The solution went ahead and wholly updated the tests. The findLastItem will work but for arrays only. That's not what the earlier tests were asking for. I know objects do not have an order based on the browser but once transformed into an Array they could work Array-ish.

Oh well ¯\_(ツ)_/¯

**Comment by Banb4n** [comment]
Hi @bhagatparwinder, it’s too bad, but the most important is to have fun 😉.
It's possible to finish it without changing the tests, I did it quickly to show you an [example of a solution](https://github.com/Banb4n/hacktoberfest-2k18-katas/pull/1/files), it is quite basic but works for Array, Strings and objects.
