### ISSUE TITLE
Implement validateNewPassword

### ISSUE THREAD

**Issue by pynnl** [rgehan/hacktoberfest-2k18-katas#252]
# validateNewPassword

### Link to the PR that adds this test case:
#251 

### Where to implement:
`src/validateNewPassword.js`

### Where are the tests:
`src/validateNewPassword.test.js`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by OZebra** [comment]
I'm on it!

**Comment by OZebra** [comment]
I had some problems with my first pull request, but i'm still on it.

**Comment by OZebra** [comment]
hey @rgehan i had some problems with the test file. When i first cloned this repository, there was no validateNewPassword.js neither the test, so the bot just rejected my pr, once that i did not modify any file.

**Comment by rgehan** [comment]
I'll release it tomorrow

**Comment by rgehan** [comment]
Hey @nip10,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @bokub, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
