### ISSUE TITLE
implement arrayElementsSubtraction

### ISSUE THREAD

**Issue by mannutech** [rgehan/hacktoberfest-2k18-katas#271]
# [arrayElementsSubtraction]

### Link to the PR that adds this test case:
[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/270]

### Where to implement:
`src/arrayElementsSubtraction.js`

### Where are the tests:
`src/arrayElementsSubtraction.test.js`

### Description (optional):
If the function is complex enough to warrant a description, add it here...

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by janczizikow** [comment]
Could I tackle this one?

**Comment by rgehan** [comment]
Go ahead
/assign @janczizikow

**Comment by janczizikow** [comment]
Hey @rgehan 

I had to modify one of the test case for the issue. The assertion expected the function to throw an Error, so without the change it would be impossible to pass the tests.
