### ISSUE TITLE
implement largestPrimeFactor

### ISSUE THREAD

**Issue by janczizikow** [rgehan/hacktoberfest-2k18-katas#275]
# largestPrimeFactor

### Link to the PR that adds this test case:
#274

### Where to implement:
`src/largestPrimeFactor.js`

### Where are the tests:
`src/largestPrimeFactor.test.js`

### Description (optional):
A prime number is a whole number greater than 1 whose only factors are 1 and itself. A factor is a whole numbers that can be divided evenly into another number. Implement the function *largestPrimeFactor*, so it will return largest prime factor for a passed number. Return `null` if the number has no prime factors.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by ktan114** [comment]
Hi, I'd like to give it a shot!

**Comment by rgehan** [comment]
Go ahead

/assign @ktan114

**Comment by rgehan** [comment]
Go ahead

/assign @ktan114
