### ISSUE TITLE
Implement evalOrQuery

### ISSUE THREAD

**Issue by vishal-wadhwa** [rgehan/hacktoberfest-2k18-katas#279]
# evalOrQuery

### Link to the PR that adds this test case:
#278

### Where to implement:
`src/evalOrQuery.js`

### Where are the tests:
`src/evalOrQuery.test.js`

### Description (optional):

1. Return an array of objects that follow the criteria specified in the query.
2. Query contains certain values mapped to operators `'<', '>' and '='`.
3. Any objects in the array that obey this criteria when compared using the comparator should be returned.
4. Comparator is a function that expects an object from the array and value to be compared with (from query) and returns `-1, 0, or 1` informing whether the object (1st argument) was less than, equal to or greater than the value (2nd argument).

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by pynnl** [comment]
Can I take this? Thanks

**Comment by rgehan** [comment]
Go ahead

/assign @pynnl

**Comment by rgehan** [comment]
Go ahead

/assign @pynnl
