### ISSUE TITLE
Implement `flatten`

### ISSUE THREAD

**Issue by TimothePearce** [rgehan/hacktoberfest-2k18-katas#28]
### Flatten

**Where to implement**: `src/flatten.js`
**Where are the tests**: `src/flatten.test.js`

Good luck :heart:

**Comment by Alfreddatui** [comment]
can I get this?

**Comment by cptjacky** [comment]
Sorry, I wanna have fun with that one so I got assigned from the start ;)

I'll ping you on the next one!
