### ISSUE TITLE
Implement `removeDuplicates`

### ISSUE THREAD

**Issue by bereninga** [rgehan/hacktoberfest-2k18-katas#282]
# removeDuplicates

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/281

### Where to implement:
`src/removeDuplicates.js`

### Where are the tests:
`src/removeDuplicates.test.js`

### Description (optional):
Remove duplicate values from an array of strings or numbers.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by tricinel** [comment]
@bereninga, I can take this if that's alright. I don't see `removeDuplicates.js` in `src` (#281 is not merged yet), but I do see `removeAllDuplicates`. Is the purpose the same?

**Comment by tricinel** [comment]
cc @rgehan ^

**Comment by rgehan** [comment]
It's a duplicate, I'll close it sorry

**Comment by tricinel** [comment]
No problemo! :)
