### ISSUE TITLE
Implement padEnd

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#284]
# padEnd

### Link to the PR that adds this test case:
#283 

### Where to implement:
`src/padEnd.js`

### Where are the tests:
`src/padEnd.test.js`

### Description (optional):
A string padding function similar to `lodash.pad`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by danie1h** [comment]
Hello, can I take up this issue?

**Comment by rgehan** [comment]
Yes go ahead

/assign @danie1h
