### ISSUE TITLE
Implement startsWith

### ISSUE THREAD

**Issue by bereninga** [rgehan/hacktoberfest-2k18-katas#285]
# startsWith

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/281

### Where to implement:
`src/startsWith.js`

### Where are the tests:
`src/startsWith.test.js`

### Description (optional):
Return `true` or `false` if an array or string starts with a given value.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by sadarshannaiynar** [comment]
Can I take this?

**Comment by rgehan** [comment]
Sorry, still a duplicate :)
