### ISSUE TITLE
Implement objectPathRetrieve

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#289]
# objectPathRetrieve

### Link to the PR that adds this test case:
#288 

### Where to implement:
`src/objectPathRetrieve.js`

### Where are the tests:
`src/objectPathRetrieve.test.js`

### Description (optional):
Implement a function that takes object and path as parameters and returns the value

```
Example 1
----------
Object: { hello: 'world', end: '!!!' }
Path: end
Output: !!!

Example 2
----------
Object: {
      name: {
        firstName: 'Foo',
        lastName: 'Bar',
      }
}
Path: name.firstName
Output: 'Foo'

Example 3
----------
Object: {
      name: {
        firstName: 'Foo',
        lastName: 'Bar',
      }
}
Path: name
Output: {
        firstName: 'Foo',
        lastName: 'Bar',
      }
```

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by roblan** [comment]
@sadarshannaiynar can I take this one?
