### ISSUE TITLE
Implement evalReversePolishNotation

### ISSUE THREAD

**Issue by EldoranDev** [rgehan/hacktoberfest-2k18-katas#297]
# evalReversePolishNotation

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/298

### Where to implement:
`src/evalReversePolishNotation.js`

### Where are the tests:
`src/evalReversePolishNotation.test.js`

### Description (optional):
This method should eval strings that are written in the Reverse Polish Notation.

See [RPN on Wikipedia](https://en.wikipedia.org/wiki/Reverse_Polish_notation) for more information on the RPN.

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Banb4n** [comment]
Can I take this?

**Comment by rgehan** [comment]
Yep /assign @Banb4n
