### ISSUE TITLE
Implement `min`

### ISSUE THREAD

**Issue by TimothePearce** [rgehan/hacktoberfest-2k18-katas#30]
### Min

**Where to implement**: `src/min.js`
**Where are the tests**: `src/min.test.js`

Good luck :heart:

**Comment by TimothePearce** [comment]
@Alfreddatui for you ?

**Comment by TimothePearce** [comment]
@dimGlyn ?

**Comment by audrius59** [comment]
Can I take this one?

**Comment by rgehan** [comment]
Yep!

**Comment by TimothePearce** [comment]
destroy it !
