### ISSUE TITLE
Implement reverseNumber

### ISSUE THREAD

**Issue by ktan114** [rgehan/hacktoberfest-2k18-katas#301]
# reverseNumber

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/299

### Where to implement:
`src/reverseNumber.js`

### Where are the tests:
`src/reverseNumber.test.js`

### Description (optional):
Reverse the input number, for example the input 123 should become 321.
----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Banb4n** [comment]
Can I take this?

**Comment by rgehan** [comment]
Yes, /assign @Banb4n
