### ISSUE TITLE
Implement isGroupByPair

### ISSUE THREAD

**Issue by Banb4n** [rgehan/hacktoberfest-2k18-katas#309]
# isGroupByPair

### Link to the PR that adds this test case:
#307 

### Where to implement:
`src/isGroupByPair.js`

### Where are the tests:
`src/isGroupByPair.test.js`

### Description (optional):
Return true if `()` | `[]` | `{}` are grouped by pair.

----

# If you want to take on this issue:
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by shmesa22** [comment]
I can work on this one

**Comment by cyng24** [comment]
if it's still up for grabs, /request

**Comment by rgehan** [comment]
Hey @cyng24, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
