### ISSUE TITLE
Implement `partition`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#31]
### Partition

**Where to implement**: `src/partition.js`
**Where are the tests**: `src/partition.test.js`
**Description**:
It acts like `lodash.partition`, but do not copy/past, it's no fun!

Thanks :heart:

**Comment by benNek** [comment]
Can I take this one?

**Comment by rgehan** [comment]
Only if you star the repo ;) Go ahead!

**Comment by benNek** [comment]
Thanks! I did haha
