### ISSUE TITLE
Implement kebabCase

### ISSUE THREAD

**Issue by danie1h** [rgehan/hacktoberfest-2k18-katas#313]
# kebabCase

### Link to the PR that adds this test case:
[#314](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/314)

### Where to implement:
`src/kebabCase.js`

### Where are the tests:
`src/kebabCase.test.js`

### Description (optional):
For a given string, return the same string in kebab case. 
Kebab case: lower case words separated by a hyphen

----

# If you want to take on this issue:
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Jaace, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Jaace** [comment]
Thanks @rgehan - it looks like @danie1h did this though and it was merged already - or am I reading that wrong?
