### ISSUE TITLE
Implement stringToBinary

### ISSUE THREAD

**Issue by Jaace** [rgehan/hacktoberfest-2k18-katas#318]
# stringToBinary

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/319

### Where to implement:

`src/stringToBinary.js`

### Where are the tests:

`src/stringToBinary.test.js`

### Description (optional):

Convert given string to binary, null on empty strings.
---

# If you want to take on this issue:

- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @jrga03, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by jrga03** [comment]
@Jaace I think the last test case has a typo. It expects a space at the end while the other tests do not.

**Comment by Jaace** [comment]
Good catch @jrga03 - feel free to change that and then in the PR makes sure you ping rhegan that you had to make that small change to the test.

Apologies for the inconvenience!

**Comment by jrga03** [comment]
@rgehan should I include the change in the test in my PR?
