### ISSUE TITLE
Implement alphabetizeString

### ISSUE THREAD

**Issue by Jaace** [rgehan/hacktoberfest-2k18-katas#320]
# alphabetizeString

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/321

### Where to implement:

`src/alphabetizeString.js`

### Where are the tests:

`src/alphabetizeString.test.js`

### Description (optional):
Re-order a given string in alphabetical order, removing whitespaces, but keeping special characters. ASCII sort order will help you.
---

# If you want to take on this issue:

- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Reserved for @brendanAlbert (once it's merged)

**Comment by rgehan** [comment]
@brendanAlbert It's now merged
