### ISSUE TITLE
Implement isSorted

### ISSUE THREAD

**Issue by kirtansakariya** [rgehan/hacktoberfest-2k18-katas#322]
# isSorted

### Link to the PR that adds this test case:

#323 

### Where to implement:

`src/isSorted.js`

### Where are the tests:

`src/isSorted.test.js`

### Description (optional):

Return `true` or `false` depending on if the list of numbers is sorted. Return `null` if any invalid input is passed in.

---

# If you want to take on this issue:

- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by mbabatunde** [comment]
Hi, could I actually take this one?

**Comment by mbabatunde** [comment]
Can I take this one please?

**Comment by rgehan** [comment]
It's not merge yet, `/request` it once it's tagged "up for grabs"

**Comment by rgehan** [comment]
Hey @cyng24, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
