### ISSUE TITLE
Implement unblockIt

### ISSUE THREAD

**Issue by pynnl** [rgehan/hacktoberfest-2k18-katas#326]
### **_\*\*\*This issue is quite challenging\*\*\*_**
# unblockIt

### Link to the PR that adds this test case:

#327 

### Where to implement:

`src/unblockIt.js`

### Where are the tests:

`src/unblockIt.test.js`

### Description:

**Description:** This function is a simple version of the popular game "Unblock It". You are required to move the desired block to reach the right edge of the boundary without crossing other blocks. Each block can only be moved in the directions along with its shape, either horizontal or vertical.

**Format:**
- A blank space is presented by a space ' '.
- Each block is presented by distinct characters.
- The desired block is presented by character X.
- The input is a starting matrix.
- The output has to be an array of matrices presenting each step.
- You are required to find the fastest answer.

**Example:**
```javascript
//start
[
  '      ',
  'AA B  ',
  'XX B  ',
  'C  B  ',
  'C     ',
  'CDDD  '
]
```
```javascript
//Move X 1 step to the right
[
  '      ',
  'AA B  ',
  ' XXB  ',
  'C  B  ',
  'C     ',
  'CDDD  '
]
```
```javascript
//Move C 1 step to the top
[
  '      ',
  'AA B  ',
  'CXXB  ',
  'C  B  ',
  'C     ',
  ' DDD  '
]
```
```javascript
//Move D 1 step to the left
[
  '      ',
  'AA B  ',
  'CXXB  ',
  'C  B  ',
  'C     ',
  'DDD   '
]
```
```javascript
//Move B all the way to the bottom
[
  '      ',
  'AA    ',
  'CXX   ',
  'C  B  ',
  'C  B  ',
  'DDDB  '
]
```
```javascript
//Move X all the way to the right
[
  '      ',
  'AA    ',
  'C   XX',
  'C  B  ',
  'C  B  ',
  'DDDB  '
]
```
---

# If you want to take on this issue:

- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @q-ata, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by q-ata** [comment]
Still working on this.

**Comment by rgehan** [comment]
Hey @q-ata,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by q-ata** [comment]
/request
Should be done tomorrow.

**Comment by rgehan** [comment]
Hey @q-ata, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by q-ata** [comment]
Confidence on a downward slope. If I can't finish today I'll give up.
