### ISSUE TITLE
Implement bleepProfanity

### ISSUE THREAD

**Issue by brendanAlbert** [rgehan/hacktoberfest-2k18-katas#329]
# [bleepProfanity]

### Link to the PR that adds this test case:

[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/328]

### Where to implement:

`src/bleepProfanity.js`

### Where are the tests:

`src/bleepProfanity.test.js`

### Description (optional):

    This function should take a string argument, change any bad words into
    words like: '$%&^' or '@$#!', and return this bleeped string!

    It's up to you what you want to consider a bad word.

    It's also up to you if you want the bleeped version of the bad word to be
    the same number of characters or a random number, so as to hide which bad
    word it might have been.

    *easy version*
      - bleep any bad words, even if they are inside another word
    
    *medium version*
      - bleep bad words only if they are stand alone and NOT inside another word

    argument: string
    return: bleeped version of string

---

# If you want to take on this issue:

- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by cyng24** [comment]
is there where I reply with /request ?

**Comment by rgehan** [comment]
Sorry, @cyng24, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.
