### ISSUE TITLE
Implement `mean`

### ISSUE THREAD

**Issue by cptjacky** [rgehan/hacktoberfest-2k18-katas#33]
### Mean

**Where to implement**: `src/mean.js`
**Where are the tests**: `src/mean.test.js`
**Description**:
The mean value of an array ;)

Thanks :heart:

**Comment by ivansieder** [comment]
I'd like to take it :)

**Comment by rgehan** [comment]
Yep !

**Comment by ivansieder** [comment]
I'mma finish it, just got back to a PC :)

**Comment by AntonStrand** [comment]
Cool, then I’ll back off ;)
