### ISSUE TITLE
Implement rotateRight

### ISSUE THREAD

**Issue by cyng24** [rgehan/hacktoberfest-2k18-katas#336]
# rotateRight

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/337

### Where to implement:

`src/rotateRight.js`

### Where are the tests:

`src/rotateRight.test.js`

### Description (optional):

Given an array, rotate the list to the right by 'n' places, where 'n' is non-negative. Return the array.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by kirtansakariya** [comment]
Hi. I'm working on this issue at the moment. It's telling me that my results are not correct enough though the array being returned is shifted the correct amount. When I run `yarn test rotateRight.test.js` I'm told that it would be better to use `toEqual` as opposed to `toBe`. Am I allowed to make this change or should I keep trying to get it to work with `toBe`?

**Comment by cyng24** [comment]
I think it's probably better to change it to toEqual
