### ISSUE TITLE
Implement wordSearch

### ISSUE THREAD

**Issue by cyng24** [rgehan/hacktoberfest-2k18-katas#340]
# wordSearch

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/341

### Where to implement:

`src/wordSearch.js`

### Where are the tests:

`src/wordSearch.test.js`

### Description (optional):

Given a 2D board and a word, find if the word exists in the grid.
EXAMPLE BOARD:
```
[
  ['A','B','C','E'],
  ['S','F','C','S'],
  ['A','D','E','E']
]
```
EXAMPLE WORD: `ABCCED`
The word can be constructed from letters of sequentially adjacent cell, where "adjacent" cells are those horizontally or vertically neighboring. The same letter cell may not be used more than once.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @brendanAlbert, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @brendanAlbert,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by brendanAlbert** [comment]
I am working on it!  I am very close to submitting a PR.

**Comment by rgehan** [comment]
Hey @brendanAlbert, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by brendanAlbert** [comment]
This comment is just to let the owner know that I am still working on this!  I just need to finish writing the test cases for the new kata.

**Comment by rgehan** [comment]
Good initiative
