### ISSUE TITLE
Implement centerText

### ISSUE THREAD

**Issue by pynnl** [rgehan/hacktoberfest-2k18-katas#362]
# centerText
### Link to the PR that adds this test case:

#361 

### Where to implement:

`src/centerText.js`

### Where are the tests:

`src/centerText.test.js`

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @kiminohero, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by Jaace** [comment]
@pynnl I believe your final test is slightly wrong, but let me know if _I'm_ the one who is wrong here.

In your final test, you have:
```
[
      ' A mad boxer shot a ',
      ' quick, gloved jab  ',
      ' to the jaw of his  ',
      '   dizzy opponent   '
    ]
```
with the `s` set to `'A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent'` and the `n` set to `20`.

This would make the test result need to be this instead:
```
[
      ' A mad boxer shot a ',
      'quick, gloved jab to',
      'the jaw of his dizzy',
      '      opponent      '
    ]
```

If you agree with this, I will update your test to match the expected result and make a note to `rgehan` in the PR.

**Comment by pynnl** [comment]
Sorry for late reply Jaace. That was my fault. Please fix it as you wish.
