### ISSUE TITLE
Implement `takeWhile`

### ISSUE THREAD

**Issue by benNek** [rgehan/hacktoberfest-2k18-katas#37]
### takeWhile

**Where to implement**: `src/takeWhile.js`
**Where are the tests**: `src/takeWhile.test.js`
**Description**:
Returns an array of items which pass the predicate

Thanks :heart:

**Comment by TimothePearce** [comment]
@sadarshannaiynar that's for you

**Comment by rgehan** [comment]
Released as the PR doesn't follow the rules.

**Comment by sandhyaagarwal** [comment]
Can I take this up ?

**Comment by TimothePearce** [comment]
@sandhyaagarwal that's for you
