### ISSUE TITLE
Implement 'chunk'

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#38]
### Name of the function

**Where to implement**: `src/chunk.js`
**Where are the tests**: `src/chunk.test.js`
**Description**:
Similar to `lodash.chunk`

Thanks :heart:

**Comment by kumaran-14** [comment]
I ll take this

**Comment by bitcolor** [comment]
I'll take it!

**Comment by rgehan** [comment]
You can go ahead @kumaran-14

**Comment by kumaran-14** [comment]
I have implemented chunk and wrote new test cases for difference
