### ISSUE TITLE
getAllPermutations

### ISSUE THREAD

**Issue by EldoranDev** [rgehan/hacktoberfest-2k18-katas#390]
# getAllPermutations

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/389

### Where to implement:

`src/getAllPermutations.js`

### Where are the tests:

`src/getAllPermutations.test.js`

### Description (optional):

Return all permutations of the given string. (See test for more details)
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @arealdeadone, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by arealdeadone** [comment]
@EldoranDev My tests are failing because the generated permutations are in a different order than what the test specifies. Is this acceptable or should it be exactly what the test specifies? i.e. is the ordering important?

**Comment by EldoranDev** [comment]
Oh, damn did not think about that, i guess I'll fix my test and order the array by alphabetical order

**Comment by arealdeadone** [comment]
What you could do is compare with sorted arrays because when numbers are present with alphabets or any other special characters they are sorted in increasing order of ASCII codes I guess.

**Comment by cptjacky** [comment]
@arealdeadone I merged the proposed fix by @EldoranDev, you should rebase on master :)

**Comment by arealdeadone** [comment]
@EldoranDev there is a typo in the test file at the import statement `import { permutation } from './getAllPermutation';` I guess it should be `import { permutation } from './getAllPermutations';`.
