### ISSUE TITLE
Implementing Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by mariannactx** [rgehan/hacktoberfest-2k18-katas#392]
# minArrayLengthSum

### Link to the PR that adds this test case:

[the url]

### Where to implement:

`src/minArrayLengthSum.js`

### Where are the tests:

`src/minArrayLengthSum.test.js`

### Description (optional):

Given an array of n positive integers and a positive integer s, find the minimal length of a contiguous subarray of which the sum ≥ s. If there isn't one, return 0 instead.

Input: s = 7, nums = [2,3,1,2,4,3]
Output: 2
Explanation: the subarray [4,3] has the minimal length under the problem constraint.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @AliNisarAhmed, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @AliNisarAhmed, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by AliNisarAhmed** [comment]
```
it('throws error when total array sum is less then the summing factor', () => {
        expect(minArrayLengthSum([2,3,1,2,4], 20)).toThrow();
    });
```

This test should be written as (as per Jest docs, it's necessary to wrap the function inside another function to check for throws)

```
it('throws error when total array sum is less then the summing factor', () => {
        expect(() => minArrayLengthSum([2,3,1,2,4], 20)).toThrow();
    });
```

@mariannactx @rgehan Please check the above test cases.
