### ISSUE TITLE
combinationModPrime

### ISSUE THREAD

**Issue by arealdeadone** [rgehan/hacktoberfest-2k18-katas#396]
# combinationModPrime

### Link to the PR that adds this test case:

[#397](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/397)

### Where to implement:

`src/combinationModPrime.js`

### Where are the tests:

`src/combinationModPrime.test.js`

### Description (optional):
Find all possible ways to choose _**k**_ objects from _**n**_ objects. Since the inputs can be large the answer should be given modulo 1000000007 i.e. if the number is greater than 1000000007 then the result should be the result of the operation `result%1000000007`.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @vishal-wadhwa, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
