### ISSUE TITLE
Fix Test cases: evenNumbersInArray

### ISSUE THREAD

**Issue by Bharat23** [rgehan/hacktoberfest-2k18-katas#399]
# [evenNumbersInArray]

### Link to the PR that adds this test case:

[ #398  ]

### Where to implement:

`src/evenNumbersInArray.js`

### Where are the tests:

`src/evenNumbersInArray.test.js`

### Description (optional):

Edit the function to pass all the test cases

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @EricLemieux, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by EricLemieux** [comment]
Running the tests locally all of the tests are passing for this function, is there a specific example of the tests not passing?

**Comment by rgehan** [comment]
They shouldn't be passing if you didn't implement anything

**Comment by EricLemieux** [comment]
`yarn run test src/evenNumbersInArray.test.js           
yarn run v1.9.4
$ jest src/evenNumbersInArray.test.js
 PASS  src/evenNumbersInArray.test.js
  evenNumbersInArray
    ✓ evenNumbersInArray returns even number (3ms)
    ✓ evenNumbersInArray returns an empty array (1ms)
    ✓ evenNumbersInArray should throw

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.645s, estimated 1s
Ran all test suites matching /src\/evenNumbersInArray.test.js/i.
Done in 1.16s.
`

**Comment by rgehan** [comment]
I think this issue shouldn't have been created. I'll close it, sorry
