### ISSUE TITLE
Implement Euler Totient Function

### ISSUE THREAD

**Issue by arealdeadone** [rgehan/hacktoberfest-2k18-katas#408]
# Euler Totient Function

### Link to the PR that adds this test case:

#409 

### Where to implement:

`src/eulerTotient.js`

### Where are the tests:

`src/eulerTotient.test.js`

### Description (optional):

Find the value of phi(n) for a given number, more details refer [here](https://en.wikipedia.org/wiki/Euler%27s_totient_function)

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @shivanggarg1998, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by shivanggarg1998** [comment]
there is some issue with test cases so can I modify them?
the issue is expect(eulerTotient(null)).toThrow(); is wrong format and right one is expect(()=>eulerTotient(null)).toThrow();

**Comment by rgehan** [comment]
Hey @shivanggarg1998,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by shivanggarg1998** [comment]
@rgehan there is some issue in test case as i have commented above

**Comment by rgehan** [comment]
Hey @shivanggarg1998, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by shivanggarg1998** [comment]
Please verify the test case or pls help me what to return in case of invalid/null number . I have already completed the function and have generated a new one

**Comment by shivanggarg1998** [comment]
ya got a workaround just returning a function with throws an error will do
