### ISSUE TITLE
Implement timeConversion

### ISSUE THREAD

**Issue by chadramsey** [rgehan/hacktoberfest-2k18-katas#415]
# timeConversion

### Link to the PR that adds this test case:

[#349](https://github.com/rgehan/hacktoberfest-2k18-katas/issues/349)

### Where to implement:

`src/timeConversion.js`

### Where are the tests:

`src/timeConversion.test.js`

### Description (optional):

Take the time parameter being passed and return the number of hours and minutes the parameter converts to (ie. if time = 121 then the output should be 2:01). Separate the number of hours and minutes with a colon. 

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @ryanmdoyle, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by chadramsey** [comment]
@rgehan Updated PR so references are now correct for this issue

**Comment by ryanmdoyle** [comment]
@rgehan 
Sorry, I'm kind of a newb here...
 Am I understanding correctly that the third change should be two files for some other problem that I think up?  (Like, I am thinking of my own kata challenge and making new files for someone else to solve?)

**Comment by ryanmdoyle** [comment]
Thanks!  Just put in the pull request.
