### ISSUE TITLE
Implement findLongestWord

### ISSUE THREAD

**Issue by garrettluu** [rgehan/hacktoberfest-2k18-katas#424]
# findLongestWord

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/423

### Where to implement:

`src/findLongestWord.js`

### Where are the tests:

`src/findLongestWord.test.js`

### Description (optional):

For any given string with spaces, return the longest word in the string.
For example, "sleepy depression sad" returns "depression".

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Frizz925, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Frizz925** [comment]
@garrettluu It seems your test case has errors in it
https://github.com/garrettluu/hacktoberfest-2k18-katas/blob/288bda3fbe40effecc4d0faa6f41f901d7fe71eb/src/findLongestWord.test.js#L23-L31

**Comment by garrettluu** [comment]
@Frizz925 So sorry about that! Silly mistakes happen, and I'm sorry for not checking my code more thoroughly before submitting my pull request. Is your PR going to get denied because you modified another file? I apologize again for my mistake.

**Comment by Frizz925** [comment]
I think it needs to be manually merged later, we'll see.
