### ISSUE TITLE
Implement _2048

### ISSUE THREAD

**Issue by hidingmode** [rgehan/hacktoberfest-2k18-katas#427]
# 2048 Game State Change

### Link to the PR that adds this test case:

#428

### Where to implement:

`src/_2048.js`

### Where are the tests:

`src/_2048.test.js`

### Description (optional):

The goal is to display the new state of the 2048 game after a move executed by the player.
2048 is a game that is played on a 4x4 grid containing integers that are powers of 2.
For details of the game, please refer to https://open.kattis.com/problems/2048

The function takes in 2 parameters:
- a 4x4 array : the initial state of the game
- an integer : the player's move (0 for left, 1 for up, 2 for right, 3 for down)

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @PandawanFr, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @PandawanFr,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @Qwerp-Derp, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @Qwerp-Derp,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @Qwerp-Derp, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @tanhauhau, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @tanhauhau,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by tanhauhau** [comment]
@rgehan i've opened a MR #779 for this issue
