### ISSUE TITLE
alternatingSums.js

### ISSUE THREAD

**Issue by AliNisarAhmed** [rgehan/hacktoberfest-2k18-katas#445]
# alternatingSums

### Link to the PR that adds this test case:

[#444](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/444)

### Where to implement:

`src/alternatingSums.js`

### Where are the tests:

`src/alternatingSums.test.js`

### Description (optional):

Several people are standing in a row and need to be divided into two teams. The first person goes into team 1, the second goes into team 2, the third goes into team 1 again, the fourth into team 2, and so on.

You are given an array of positive integers - the weights of the people. Return an array of two integers, where the first element is the total weight of team 1, and the second element is the total weight of team 2 after the division is complete.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @bhagatparwinder, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
