### ISSUE TITLE
Implement 'removeConsecutiveDuplicates'

### ISSUE THREAD

**Issue by tatchi** [rgehan/hacktoberfest-2k18-katas#45]
### Name of the function

**Where to implement**: `src/removeConsecutiveDuplicates.js`
**Where are the tests**: `src/removeConsecutiveDuplicates.test.js`
**Description**:
Remove all consecutive duplicate values from an array

Thanks :heart:

**Comment by bitcolor** [comment]
I'll take it

**Comment by kumaran-14** [comment]
I ll do it

**Comment by TimothePearce** [comment]
@bitcolor it is yours 👍

**Comment by TimothePearce** [comment]
Well in fact you already have https://github.com/rgehan/hacktoberfest-2k18-katas/issues/47 so @kumaran-14 let's go it is your turn

**Comment by piksu** [comment]
I'd like to take this one. To clarify, input [1,2,3,3,4,4,5] should produce the output [1,2,3,4,5]?

**Comment by GuilhermeBaule** [comment]
I think yes.. [1,2,3,3,4,5,1] shuld produce [1,2,3,4,5,1], it just need to remove the sequential duplicated

**Comment by rgehan** [comment]
Released as the PR is now inactive

**Comment by piksu** [comment]
I headed to sleep and I am online now again. Let me finish this up by reopening the issue?

**Comment by rgehan** [comment]
You can take it yes :)

**Comment by kumaran-14** [comment]
This was open too long? can i have a go at this?

**Comment by rgehan** [comment]
@piksu Do you still want it?
