### ISSUE TITLE
Minor bug: isAnagram

### ISSUE THREAD

**Issue by wmik** [rgehan/hacktoberfest-2k18-katas#452]
Great project!
Minor bug in [isAnagram](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/src/isAnagram.js)

**`test`**
```js
expect(isAnagram("cat", "cat")).toBeFalsy(); // fails
```

**Comment by x3tsunayh** [comment]
I'd like to take this up!
/request

**Comment by rgehan** [comment]
Sorry, @x3tsunayh, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
@wmik I guess you're right, a word cannot be an anagram of itself.

If you want to submit a PR to fix it, I guess you can

**Comment by rgehan** [comment]
I'll still close the issue as it isn't a kata
