### ISSUE TITLE
Implement doYouKnowDaWae

### ISSUE THREAD

**Issue by vishal-wadhwa** [rgehan/hacktoberfest-2k18-katas#454]
# Implement doYouKnowDaWae

### Link to the PR that adds this test case:

#453

### Where to implement:

`src/doYouKnowDaWae.js`

### Where are the tests:

`src/doYouKnowDaWae.test.js`

### Description (optional):
Many brave, Ugandan Warriors formed by a group of Knuckles, asking if they know the way. You're given a list of integers you've to find if they can go from top left cell to the bottom right cell. Remember they can only stand on those cells	which have 1 in their binary representation at that cell. The binary representation has a width represented by the 2nd argument. YOU CAN ONLY MOVE LEFT, RIGHT, TOP OR DOWN. Now, you've been asked, do you know da wae? Answer `true` or `false`.

Example: 
```
arr = [2, 2]
colw = 2
```
Since, `colw = 2`, binary representation of each number in `arr` will have length as `2`. So, our path matrix is like:
```
10
10
```
Since, cell at `(0, 0)` is `1` the warriors can stand on it, but the target cell at `(1, 1)` is `0`, so, they cannot reach their destination and you function must return false.

**Source is always top left. Destination is always bottom right.**

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @pszczolas, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
