### ISSUE TITLE
Implement isIsomorphic

### ISSUE THREAD

**Issue by nip10** [rgehan/hacktoberfest-2k18-katas#457]
# isIsomorphic

### Link to the PR that adds this test case:

#458 

### Where to implement:

`src/isIsomorphic.js`

### Where are the tests:

`src/isIsomorphic.test.js`

### Description (optional):

Given two strings, return true/false whether they are isomorphic or not.
Strings are isomorphic if all occurrences of a character in string A can be replaced with another character to get to string B. The order of each character must be preserved. Every char in string A must have a 1-to-1 mapping to every char in string B.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @absat, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
