### ISSUE TITLE
Implement Rotate String

### ISSUE THREAD

**Issue by mandardeshpande** [rgehan/hacktoberfest-2k18-katas#464]
# [rotateString]

### Link to the PR that adds this test case: https://github.com/rgehan/hacktoberfest-2k18-katas/pull/463

[the url]

### Where to implement:

`src/rotateString.js`

### Where are the tests:

`src/rotateString.test.js`

### Description (optional):

**Given two Strings A and B.**

A shift on **"A"** string consists of taking a string **"A"** and moving the leftmost character to the rightmost position. For example if **A='abcde**' then it will be 'bcdea' after one shift on "A". Return true if and only if A can become B after some number of shifts on A.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @MrWako, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @chadramsey, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by chadramsey** [comment]
/assign @MrWako 

Apologies, was demoing this repo to someone else and accidentally commented. @MrWako this one is all yours.

**Comment by rgehan** [comment]
Hey @chadramsey,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Sorry @Haugum, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @chgasparoto, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
