### ISSUE TITLE
Implement `isPalindrome`

### ISSUE THREAD

**Issue by sajadhsm** [rgehan/hacktoberfest-2k18-katas#47]
### isPalindrome

**Where to implement**: `src/isPalindrome.js`
**Where are the tests**: `src/isPalindrome.test.js`
**Description**:
Checks if a string is [Palindrome](https://en.wikipedia.org/wiki/Palindrome)

Thanks :heart:

**Comment by bitcolor** [comment]
I'll take it

**Comment by mohit2016** [comment]
I can work on this

**Comment by cptjacky** [comment]
@bitcolor It's all yours!
