### ISSUE TITLE
Implement testFrame

### ISSUE THREAD

**Issue by pszczolas** [rgehan/hacktoberfest-2k18-katas#473]
# textFrame

### Link to the PR that adds this test case:

[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/474](url)

### Where to implement:

`src/textFrame.js`

### Where are the tests:

`src/textFrame.test.js`

### Description (optional):

Text frame is made from 4 strings which create rectangle.
Two of them are pleced horizontal and the remaning two vertical.
First letter of top-horizontal word must be the same as first letter of left-vertical word.
Last letter of top-horizontal word must be the same as first letter of right-vertical word.
First letter of bottom-horizontal word must be the same as last letter of left-vertical word.
Last letter of bottom-horizontal word must be the same as last letter of right-vertical word.
Inside the frame must be an empty space.

Example:
From: "abcd", "bcad", "daad", "aaab"
Text frame with empty space inside can be created:

```
abcd
a  a
a  a
bcad
```

Your task is to determine if it is possible to create text frame.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by q-ata** [comment]
@pszczolas I have a question, why should the test case `"john", "wick", "jigsaw", "hijack"` return true?
I understand you can do:
```
john
i
g
s
a
wick
```
But for `hijack` to fill the last edge `john` would have to end with `h` wouldn't it?

**Comment by pszczolas** [comment]
@q-ata Of course you are right. This test case should have example from this issue ("abcd", "bcad", "daad", "aaab"). Unfortunately I have forgotten to updated it in `src/textFrame.test.js` when i realized it is incorrect.

@rgehan What is correct way to fix broken test case? Should I do normal PR or maybe someone can just modify this test case during implementation?

**Comment by rgehan** [comment]
Hey @rmcguire6, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @rmcguire6,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @suyasha0, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by suyasha0** [comment]
Still working on this.

**Comment by rgehan** [comment]
Hey @suyasha0,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @suyasha0, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @suyasha0,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @q-ata, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
