### ISSUE TITLE
Implement isValidSchedule

### ISSUE THREAD

**Issue by brendanAlbert** [rgehan/hacktoberfest-2k18-katas#476]
# isValidSchedule

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/475

### Where to implement:

`src/isValidSchedule.js`

### Where are the tests:

`src/isValidSchedule.test.js`

### Description (optional):

      argument: an array of objects
      returns: boolean

      - isValidSchedule takes an array of objects.
      - each object represents a class and is of the form: 
        {'day':'mwf', 'name':'english101', 'timeBegin':800, 'timeEnd':850}
      - the times are in 24-hour clock time.  noon = 1200, 11 pm = 2300
      - 8 o'clock a.m. is represented by the integer 800
      - 8:50 a.m. is represented by the integer 850
      - 2 p.m. would be 1400

      - The other important attribute is the key/value pair 'day.
      - A class that meets on mondays and wednesdays would be, 'day': 'mw'
      - A class that meets only on tuesday would be, 'day': 't'
      - A class that meets only on thursday would be, 'day': 'h'
      - A class that meets on tuesdays and thursdays would be, 'day': 'th'
      - A class that meets on monday, wednesday and friday would be, 'day': 'mwf'

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @x3tsunayh, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
