### ISSUE TITLE
Implement powerAndCombine

### ISSUE THREAD

**Issue by nai888** [rgehan/hacktoberfest-2k18-katas#482]
# powerAndCombine

### Link to the PR that adds this test case:

#483

### Where to implement:

`src/powerAndCombine.js`

### Where are the tests:

`src/powerAndCombine.test.js`

### Description (optional):

Given three numbers `(x, y, n)`, split `x` into separate digits, raise each digit to the `y` power, add the results together, and repeat the process `n` times. Return the `n`th result.

For example, given `powerAndCombine(123, 3, 3)`:
`123` → `1^3 + 2^3 + 3^3 = 36` → `3^3 + 6^3 = 243` → `2^3 + 4^3 + 3^3 = 99`

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Frizz925, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
