### ISSUE TITLE
Implement addBigIntegers

### ISSUE THREAD

**Issue by q-ata** [rgehan/hacktoberfest-2k18-katas#487]
# addBigIntegers

### Link to the PR that adds this test case:
#485 

### Where to implement:
`src/addBigIntegers.js`

### Where are the tests:
`src/addBigIntegers.test.js`

#### Input
The first line of input, _n_, will be an integer less than or equal to 12 and greater than 1 (1 < _n_ <= 12).
The next _n_ lines will contain a positive integer less than or equal to 60 digits in length.
#### Output
The function should return the sum of the _n_ integers as a string.
#### Example
_Input:_
```
3
539
8
201
```
_Output:_
```
748
```

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Mitchell0625, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @Mitchell0625,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @GunnarHolwerda, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by GunnarHolwerda** [comment]
I would like to bring up that the first test for this kata is actually incorrect if you add up the 4 numbers: `3`, `539`, `8`, and `201` add up to `751` not `748` like the test expects
