### ISSUE TITLE
Implement Sentiment Analysis

### ISSUE THREAD

**Issue by Frizz925** [rgehan/hacktoberfest-2k18-katas#491]
# sentimentAnalysis

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/489

### Where to implement:

`src/sentimentAnalysis.js`

### Where are the tests:

`src/sentimentAnalysis.test.js`

### Description (optional):

* The outer function takes in a training data.
* The training data contains sentiment scores for a set of words.
* The outer function returns inner function which will be used to take in a sequence of words to analyze.
* The sequence to analyze doesn't need sanitization, only tokenization.
* Words not observed from the training data may be considered as neutral, as such they won't affect the weight of the analysis score.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @rgehan, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
This one looks fun, I'll do it myself :)
