### ISSUE TITLE
Implement collatzFunction

### ISSUE THREAD

**Issue by x3tsunayh** [rgehan/hacktoberfest-2k18-katas#499]
# collatzFunction

### Where to implement:

`src/collatzFunction.js`

### Where are the tests:

`src/collatzFunction.test.js`

### Description:

You can read more about the Collatz conjecture here:
https://en.wikipedia.org/wiki/Collatz_conjecture

The general idea:
- if the number is even, divide it by two
- if the number is odd, triple it and add one
- return the number of steps required for the integer input to reach 1
- return -1 if given input is invalid

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @jrga03, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
