### ISSUE TITLE
Implement `multiply`

### ISSUE THREAD

**Issue by TimothePearce** [rgehan/hacktoberfest-2k18-katas#5]
@dimGlyn that's for you bro'

ding dong, tee-shirt is coming

**Comment by chgasparoto** [comment]
I'm on it

**Comment by rgehan** [comment]
@chgasparoto will do it

**Comment by dimGlyn** [comment]
I was too late 😢

**Comment by cptjacky** [comment]
No news for a few hours and missing a few things.

I'm releasing that issue for someone else to take.

**Comment by AntonStrand** [comment]
I'll take it if it's okay.

**Comment by cptjacky** [comment]
It's all yours @AntonStrand ! :)

**Comment by AntonStrand** [comment]
Thanks! PR and a new issue has been added.
