### ISSUE TITLE
Implement isValidGaloisFieldSize

### ISSUE THREAD

**Issue by x3tsunayh** [rgehan/hacktoberfest-2k18-katas#501]
# isValidGaloisFieldSize

### Where to implement:

`src/isValidGaloisFieldSize.js`

### Where are the tests:

`src/isValidGaloisFieldSize.test.js`

### Description:

You can read more about the Galois field here:
https://en.wikipedia.org/wiki/Finite_field

The general idea:
- a valid Galois field size is a prime number to the power of a positive integer
- that is, p^i is a valid size where p is a prime number and i is a positive integer
- return true if valid Galois field size
- return false if not valid Galois field size

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @dineshvgp, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @dineshvgp,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @MartinSeibert, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by MartinSeibert** [comment]
I might need another day for this one, I'm working through the mathematics of the problem.

**Comment by rgehan** [comment]
Hey @MartinSeibert,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by MartinSeibert** [comment]
@rgehan I had an issue with my pull request. If I get this assigned back to me I'm ready to fix the issue and open a new pull request.

**Comment by rgehan** [comment]
Hey @Di3trich, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
