### ISSUE TITLE
Implement booleanExpressionEvaluator

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#507]
# booleanExpressionEvaluator

### Link to the PR that adds this test case:
#506 

### Where to implement:
`src/booleanExpressionEvaluator.js`

### Where are the tests:
`src/booleanExpressionEvaluator.test.js`

### Description:
Evaluate a boolean expression given as string

Expression contains combination of the following:

Parameter | Explanation
--- | ---
true | Denotes boolean true value
false | Denotes boolean false value
& | Boolean AND operation
\| | Boolean OR operation
! | Boolean NOT operation
^ | Boolean XOR operation

```
Examples:

Input: !true
Output: false

Input: true | true
output: true

Input: false ^ true | false
output: true
```

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
⚠️ I'll add that this one should be implemented without using `eval()` ⚠️

**Comment by KumarManoj-S** [comment]
Can I take this?

**Comment by rgehan** [comment]
Yes you can but do not use `eval`

/assign @KumarManoj-S

**Comment by rgehan** [comment]
Hey @KumarManoj-S,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by sadarshannaiynar** [comment]
@rgehan I think this issues requires some time to solve can you extend it to another 24 hours for @KumarManoj-S ?

**Comment by rgehan** [comment]
I've modified the auto release bot so that it ignores issues with the `no auto reset` label.

You're safe for now :)

**Comment by sadarshannaiynar** [comment]
@rgehan Thanks :)

**Comment by rgehan** [comment]
@sadarshannaiynar How are you doing with this challenge?

**Comment by sadarshannaiynar** [comment]
@rgehan I posted this issue probably you meant to ask @KumarManoj-S?

**Comment by rgehan** [comment]
Yep totally

**Comment by sadarshannaiynar** [comment]
@KumarManoj-S you want some time?

**Comment by sadarshannaiynar** [comment]
@rgehan reset this issue there in no reply from the assignee for the past 3 days. I guess someone else can pick it up.

**Comment by rgehan** [comment]
Yep I guess you're right;

I'll do it, this looks like fun :)

/request

**Comment by rgehan** [comment]
Sorry, @rgehan, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Defeated by my own bot :p /reset

**Comment by rgehan** [comment]
Hey @rgehan, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by sadarshannaiynar** [comment]
@rgehan Haha. Good luck. :)

**Comment by rgehan** [comment]
@sadarshannaiynar It was fun to do :)

If you want to have a look at how I've done it https://github.com/rgehan/hacktoberfest-2k18-katas/pull/663

**Comment by sadarshannaiynar** [comment]
@rgehan That's a pretty neat solution. 👍 😄 . Code was elegant and self-explanatory. But I guess you can remove that `stringifyAst` function. It's not used anywhere.
