### ISSUE TITLE
Implements `fizzBuzz`

### ISSUE THREAD

**Issue by AntonStrand** [rgehan/hacktoberfest-2k18-katas#51]
### fizzBuzz

**Where to implement**: `src/fizzBuzz.js`
**Where are the tests**: `src/fizzBuzz.test.js`
**Description**:
Every number in an array divisible by 3 should be changed to 'fizz' and every number divisible by 5 should be changed to 'buzz'. If the number is divisible by both 3 and 5, it should be changed to 'fizzbuzz'. All other numbers should be left untouched.

**Comment by benNek** [comment]
I'll take it :)

**Comment by TimothePearce** [comment]
go for it @benNek

**Comment by benNek** [comment]
I'm pretty sure that tests were wrong, so I will have to fix them too.

`expect(fizzBuzz([1, 2, 3])).toBeTruthy([1, 2, 'fizz'])`

Can anyone confirm if this not supposed to work?

**Comment by AntonStrand** [comment]
Yeah, I just realized that I probably should have used `.toEqual` instead. I just used the generated code and didn't think too much about it.

**Comment by TimothePearce** [comment]
Sorry, my fault. I missed it during the review

**Comment by benNek** [comment]
No problem, I've changed it with my PR
