### ISSUE TITLE
Implement Find the Odd occurrence number

### ISSUE THREAD

**Issue by KumarManoj-S** [rgehan/hacktoberfest-2k18-katas#511]
# Find the odd occurrence

### Link to the PR that adds this test case:

[#503](https://github.com/rgehan/hacktoberfest-2k18-katas/issues/503)

### Where to implement:

`src/findTheOddOccurence.js`

### Where are the tests:

`src/findTheOddOccurence.test.js`

### Description:
Find the number which occurred odd number of times

Example 1:
[1, 2, 1] -> 2

Example 2:
[1, 2, 1, 2, 1, 3, 1] -> 3

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @AlexandreInsua, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.
