### ISSUE TITLE
Implement numberVowels

### ISSUE THREAD

**Issue by nai888** [rgehan/hacktoberfest-2k18-katas#516]
# numberVowels

### Link to the PR that adds this test case:

#517

### Where to implement:

`src/numberVowels.js`

### Where are the tests:

`src/numberVowels.test.js`

### Description (optional):

Find the word(s) in a string with the most vowels.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @hasykes, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by hasykes** [comment]
Hi @nai888 and @rgehan, 

I think there is an issue with "src/numberVowels.test.js".  The current test is comparing an object with  .toBe() instead of .toEqual() resulting in a constant fail as my object will not be the exact same object as the test object.

From my output:

    Expected: {"most": ["Hello", "Thomas"], "number": 2}
    Received: {"most": ["Hello", "Thomas"], "number": 2}

    Difference:

    Compared values have no visual difference. Note that you are testing for equality with the stricter 
   `toBe` matcher using `Object.is`. For deep equality only, use `toEqual` instead.

How should we proceed?

**Comment by nai888** [comment]
@hasykes shoot, sorry about that. I'll readily admit, I'm pretty new to Jest, so that wasn't a difference I was aware of. I'll see if I can edit it with a new pull request.

**Comment by nai888** [comment]
@hasykes it should be updated now!

**Comment by hasykes** [comment]
> @hasykes shoot, sorry about that. I'll readily admit, I'm pretty new to Jest, so that wasn't a difference I was aware of. I'll see if I can edit it with a new pull request.

I wouldn't have known the difference had I not run into the issue, so no worries at all.  If anything it made this more of a learning experience for the both of us.  Thanks for the quick response @nai888!
