### ISSUE TITLE
Implement runBrainfuck

### ISSUE THREAD

**Issue by Zeroji** [rgehan/hacktoberfest-2k18-katas#524]
# runBrainfuck

### Link to the PR that adds this test case:

#522 

### Where to implement:

`src/runBrainfuck.js`

### Where are the tests:

`src/runBrainfuck.test.js`

### Description:

Create a [Brainfuck](https://en.wikipedia.org/wiki/Brainfuck#Language_design) interpreter.
There are no hard specifications on the interpreter, but it must properly handle the basic instruction set (`+-><.,[]`) and accept optional input as a second argument. Input and output are expected to be strings.
Don't bother setting the memory array to 30 000 cells, 10 cells are enough for those tests.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @DanielRamosAcosta, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by DanielRamosAcosta** [comment]
Done! @Zeroji 🎉
