### ISSUE TITLE
Implement twitterBlockMessageGenerator

### ISSUE THREAD

**Issue by trevorkirpaul** [rgehan/hacktoberfest-2k18-katas#535]
# twitterBlockMessageGenerator

### Link to the PR that adds this test case:

[#534](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/534)

### Where to implement:

`src/twitterBlockMessageGenerator.js`

### Where are the tests:

`src/twitterBlockMessageGenerator.test.js`

### Description (optional):

- create a function which generates an array of objects containing a message to send to twitter accounts before blocking them

- `customMessage` is required and the returned object must contain the account name and `customMessage`

- twitter account names must be validated

- valid account names:
-- are no longer than 15 characters
-- can only contain alphnumeric characters (with the exception of underscores)

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Neatoro, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Neatoro** [comment]
The provided tests are not working because the failure cases and the check for throws are not written correctly. What can I do here? Just adapt the tests?

**Comment by trevorkirpaul** [comment]
Hmm, I had hoped I wrote them correctly.

I had the same issue with the function I made so I had to fix the test
cases and I mentioned it in the PR I made.

**Comment by Neatoro** [comment]
Okay I will do the same :)

**Comment by trevorkirpaul** [comment]
Sorry about that! If you ever have the time, please let me know what the
issues were, or ping me in the PR! Thanks!
