### ISSUE TITLE
diceRoll()

### ISSUE THREAD

**Issue by ryanmdoyle** [rgehan/hacktoberfest-2k18-katas#540]
# diceRoll()

### Where to implement:

`src/diceRoll.js`

### Where are the tests:

`src/diceRoll.test.js`

### Description (optional):

Create a function that will take an argument that represents the number of sides the dice has (3 sided, 6 sides, 12, sides, etc.) and returns a random integer within that range.
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Haugum, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Haugum** [comment]
Hi Hi @ryanmdoyle888 and @rgehan, there seems to be an issue with diceRoll.test.js, as even simply returning 1, which should pass all tests automatically, is failing:

```TypeError: Cannot read property 'be' of undefined```. This issue is therefore not solvable. The test needs to be rewritten first.

**Comment by rgehan** [comment]
@Haugum Fixed in 1cc4dcb

**Comment by ryanmdoyle** [comment]
Hey @Haugum sorry about that.  This is the first time (the last week) I've written tests and I thought I was doing it correctly for a range but, apparently not!

**Comment by rgehan** [comment]
Hey @Haugum,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by paolaguarasci** [comment]
Can I try? =D

**Comment by rgehan** [comment]
Hey @steaward,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @sadarshannaiynar, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
