### ISSUE TITLE
Implement medianOfTwoArrays

### ISSUE THREAD

**Issue by Haugum** [rgehan/hacktoberfest-2k18-katas#543]
# medianOfTwoArrays

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/542

### Where to implement:

`src/medianOfTwoArrays.js`

### Where are the tests:

`src/medianOfTwoArrays.test.js`

### Description (optional):

If the function is complex enough to warrant a description, add it here...

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @outofgamut, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @outofgamut,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @AliNisarAhmed, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by AliNisarAhmed** [comment]
One test case is wrong

`it('computes the correct median of [1,2] and [2,4]', () => {
    const result = medianOfTwoSortedArrays([1,2], [2,4])
    expect(result).toEqual(2.5)  
  });`

it should be 

`it('computes the correct median of [1,2] and [3,4]', () => {
    const result = medianOfTwoSortedArrays([1,2], [2,4])
    expect(result).toEqual(2.5)  
  });`

Median of 1, 2, 3, 4 is 2.5

Median of 1, 2, 2, 4 is 2.

I will change the test to the former.
