### ISSUE TITLE
Implement stringFormatter

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#563]
# stringFormatter

### Link to the PR that adds this test case:
#562 

### Where to implement:
`src/stringFormatter.js`

### Where are the tests:
`src/stringFormatter.test.js`

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @MrWako, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by MrWako** [comment]
working on this one

**Comment by MrWako** [comment]
just need to find a new challenge now

**Comment by sadarshannaiynar** [comment]
Have you finished this @MrWako

**Comment by MrWako** [comment]
have completed the challenge just setting up the new one, sorry for the delay!

**Comment by rgehan** [comment]
No problems, don't worry it's all a game after all :)

**Comment by sadarshannaiynar** [comment]
No problems @MrWanko
