### ISSUE TITLE
Implement brainf**k

### ISSUE THREAD

**Issue by Qwerp-Derp** [rgehan/hacktoberfest-2k18-katas#592]
# brainf**k

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/593

### Where to implement:

`src/brainf.js`

### Where are the tests:

`src/brainf.test.js`

### Description (optional):

Your task is to implement brainf**k in JavaScript.

Brainf**k operates on a 30,000-cell long tape, with each cell containing a value from 0 to 255. You start off on the 0th cell, and you can move between cells to increase and decrease their values.

You can "wrap around" the tape, meaning that you can go left from the 0th cell and end up on the last cell. The cell's values also wrap around, meaning if you subtract 1 from 0 it ends up as 255.

There are 8 main instructions in BF:
- `+`: increases the value of the current cell by 1
- `-`: decreases the value of the current cell by 1
- `>`: you move 1 cell to the right
- `<`: you move 1 cell to the left
- `,`: takes an input from 0 to 255 and places it at the cell you're currently on
- `.`: takes the value of the cell you're currently on and outputs a number from 0 to 255
- `[`: begins a loop
- `]`: jumps back to the matching `[` in the program if the cell you're currently on is not 0

So, for example, in `[[]]`, the inner `[]` is a loop (so the first right bracket jumps to the second left bracket), whereas `[..]` is also a loop (the second right bracket jumps to the first left bracket).

`brainf()` takes two arguments:
- the program as a string
- a list of numbers from 0 to 255, which acts as the input for the program (defaults to [])

It must return an array of integers as output, based on the order when `.` is called. For example:

```
+++.<-.
```

The above code sample returns [3, 255], since the first `.` returns a value of `3` on
the 0th cell, and we're subtracting 1 from the 29,999th cell and outputting that, which
returns `255`.

For more details, go to [this website](https://esolangs.org/wiki/Brainfuck).
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Zeroji** [comment]
I've already made a `runBrainfuck` issue (#524, has been implemented)
Don't know if your specification can be considered different enough

**Comment by Qwerp-Derp** [comment]
@Zeroji Nah, probably can't be considered different, it's too similar. I'll come up with something else instead.
