### ISSUE TITLE
minesweeper.js

### ISSUE THREAD

**Issue by AliNisarAhmed** [rgehan/hacktoberfest-2k18-katas#600]
# [minesweeper.js]

### Link to the PR that adds this test case:

[#599](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/599)

### Where to implement:

`src/minesweeper.js`

### Where are the tests:

`src/minesweeper.test.js`

### Description (optional):

If the function is complex enough to warrant a description, add it here...

Generate a minesweeper board given the matrix: 

In the popular Minesweeper game you have a board with some mines and those cells that don't contain a mine have a number in it that indicates the total number of mines in the neighboring cells. Starting off with some arrangement of mines we want to create a Minesweeper game setup.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @rambii, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
