### ISSUE TITLE
isValidPalindrome

### ISSUE THREAD

**Issue by WeiChienHsu** [rgehan/hacktoberfest-2k18-katas#604]
# isValidPalindrome

### Link to the PR that adds this test case:

[#603](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/603)

### Where to implement:

`src/isValidPalindrome.js`

### Where are the tests:

`src/isValidPalindrome.test.js`

### Description (optional):

Given a string, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases. (Dismiss the space)

#### Example1

```
Input: "aba"
Output: True

Input: "   aba"
Output: True
```

#### Example2

````
Input: "aac"
Output: False

Input: "    abcc"
Output: False
````

#### For the purpose of this problem, we define empty string as invalid palindrome.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @aparrett, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by WeiChienHsu** [comment]
@aparrett Thanks for taking this challenge. Happy coding!
