### ISSUE TITLE
twoSum

### ISSUE THREAD

**Issue by lzhang-cbi** [rgehan/hacktoberfest-2k18-katas#615]
# twoSum

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/614

### Where to implement:

`src/twoSum.js`

### Where are the tests:

`src/twoSum.test.js`

### Description (optional):
A function that returns the position of two numbers in the first param that sums up to the number in the second param.
For example:
twoSum([1, 2, 3], 4) would return 0 and 2 since 1 and 3 returns 4 and they are in position 0 and 2.
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @lowkorn, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by kartikpandey2** [comment]
@lzhang-cbi  what two sum function do .?

**Comment by lzhang-cbi** [comment]
> @lzhang-cbi what two sum function do .?

I updated the Issue with details

**Comment by kartikpandey2** [comment]
@lzhang-cbi maybe `https://github.com/rgehan/hacktoberfest-2k18-katas/pull/614/files#diff-730e85e143fa29b1f23c372b28ced4c2R32` this test is wrong 🤔

**Comment by rgehan** [comment]
Hey @lowkorn,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by lzhang-cbi** [comment]
@kartikpandey2 ooopppss, sorry 😭, looks like someone already made a PR to fix it.

**Comment by rgehan** [comment]
Hey @Jonathan-Montanez,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @leodevo, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
