### ISSUE TITLE
Number of Common Prime Factors

### ISSUE THREAD

**Issue by shhac** [rgehan/hacktoberfest-2k18-katas#617]
# numCommonPrimeFactors

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/616

### Where to implement:

`src/numCommonPrimeFactors.js`

### Where are the tests:

`src/numCommonPrimeFactors.test.js`

### Description (optional):

Please implement a function which counts the number of prime factors shared between two given numbers.
For example: The prime factors of `60` are `2`, `2`, `3` and `5`, the prime factors of `24` are `2`, `2`, `2` and `3`; therefore, the number of common prime factors is `3`, (`2`, `2` and `3`).

This function lets you find co-primes nicely, as they share `0` common factors even if they are not prime themselves, e.g. `4` and `9` are co-prime, and would have a return of `0` from this function.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Di3trich, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
