### ISSUE TITLE
Implement `uniq`

### ISSUE THREAD

**Issue by benNek** [rgehan/hacktoberfest-2k18-katas#62]
### uniq

**Where to implement**: `src/uniq.js`
**Where are the tests**: `src/uniq.test.js`
**Description**:
Returns array with only unique values

Thanks :heart:

**Comment by AntonStrand** [comment]
I'll take it! if it's okay?

**Comment by AntonStrand** [comment]
I promise to implement the tests correctly this time ;)

**Comment by rgehan** [comment]
Yep go ahead!

**Comment by AntonStrand** [comment]
To be able to pass the tests I have to make a change to one of the tests if that's okay?
There is a bug in the test as it is right now. The second `array` should be `result`.

```it('Returns array with unique values', () => {
    var array = [1, 2, 3, 4, 5, 6, 6];
    var array = [1, 2, 3, 4, 5, 6];
    expect(uniq(array)).toEqual(result);
  });```

**Comment by rgehan** [comment]
Yep that's totally fine, good catch!
