### ISSUE TITLE
Check Valid Brackets

### ISSUE THREAD

**Issue by Di3trich** [rgehan/hacktoberfest-2k18-katas#620]
# validBrackets

### Link to the PR that adds this test case:

[#619](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/619)

### Where to implement:

`src/validBrackets.js`

### Where are the tests:

`src/validBrackets.test.js`

### Description (optional):

Implement a function that returns `'VALID'` if an expression has balanced brackets and `'INVALID'` in other way.

A bracket is considered to be any one of the following characters: `(`, `)`, `{`, `}`, `[`, or `]`, any other character should be ignored.

Two brackets are considered to be balanced if the an opening bracket (i.e., `(`, `[`, or `{`) occurs to the left of a closing bracket (i.e., `)`, `]`, or `}`) of the exact same type.

## Examples:

`validBrackets('a[b]c') => 'VALID'`
`validBrackets('a[(b){c}]d') => 'VALID'`
`validBrackets('({[]})') => 'VALID'`
`validBrackets('((())') => 'INVALID'`
`validBrackets('([)]') => 'INVALID'`

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @anands, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Sorry @t-gok, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.
