### ISSUE TITLE
Implement mazes

### ISSUE THREAD

**Issue by q-ata** [rgehan/hacktoberfest-2k18-katas#622]
# mazes

### Link to the PR that adds this test case:

#621 

### Where to implement:

`src/mazes.js`

### Where are the tests:

`src/mazes.test.js`

### Description (optional):

You are playing a video game where you are trying to navigate a maze (more like a grid). Unfortunately, your fingers are particularly large and you keep messing up the controls. Given the controls entered, determine where your player will end up.

The first line will contain two space separated integers. They are the width and height of the grid your player is in.
The second line will contain two space separated integers. They are where your player starts.
The next line will contain a single integer, *n*. This is the number of boulders on the grid. These boulders cannot be passed through.
The next *n* lines will contain two space separated integers representing the coordinates of the boulders.
The rest of the input contains one letter on each line, U, D, L or R, representing up, down, left and right respectively.
The player cannot move past the bounds of the maze nor can it travel through boulders.
Determine the final position of the player and return it as two space separated integers.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @shafeef901, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @shafeef901,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @shhac, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
