### ISSUE TITLE
Implement isPerfectNumber

### ISSUE THREAD

**Issue by kokkonisd** [rgehan/hacktoberfest-2k18-katas#627]
# isPerfectNumber

### Link to the PR that adds this test case:

[PR link](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/628)

### Where to implement:

`src/isPerfectNumber.js`

### Where are the tests:

`src/isPerfectNumber.test.js`

### Description (optional):

Checks if the number passed in as an argument is a [perfect number](https://en.wikipedia.org/wiki/Perfect_number).

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Prabhnith** [comment]
Hey I would like to work on it.

**Comment by kokkonisd** [comment]
> Hey I would like to work on it.

You need to comment "/request" to request this issue. Check out the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) before contributing.

**Comment by rgehan** [comment]
Hey @kokkonisd, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by kokkonisd** [comment]
@rgehan sorry, didn't mean to assign it to myself, just wanted to tell @Prabhnith how he should go about tackling this kata.

**Comment by rgehan** [comment]
Hey @kokkonisd,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @alex-gale, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
