### ISSUE TITLE
every

### ISSUE THREAD

**Issue by vidocco** [rgehan/hacktoberfest-2k18-katas#639]
# every 

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/640

### Where to implement:

`src/every.js`

### Where are the tests:

`src/every.test.js`

### Description (optional):

re-implement the every function from the JS standard library.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @dapilcher, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by dapilcher** [comment]
@rgehan @vidocco 
I'd like to amend the test for this function. 

Specifically in this assertion: 
```
it('shortcircuits and stops iterating if an element does not meet the condition', () => {
  let count = 0
  expect(every(arr, el => {
    count++
    return el > 2
  })).toBeFalsy()
  expect(count).toEqual(2)
});
```

In order to properly emulate `Array.prototype.every()` it should either begin with `let count = 1` or end with the assertion `expect(count).toEqual(1)`.

**Comment by rgehan** [comment]
Yes go ahead, if this fixes the tests it's okay
