### ISSUE TITLE
Track7Dev | Prime List

### ISSUE THREAD

**Issue by Track7Dev** [rgehan/hacktoberfest-2k18-katas#646]
# [Prime List]

### Link to the PR that adds this test case: 
[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/645]()

### Where to implement:

`src/primelist.js`

### Where are the tests:

`src/primelist.test.js`

### Description (optional):
```
# ERROR HANDLING:
#   Return "invalid range" for:
#     *Negative Numbers
#     *NAN (Not A Number) Data Types
#     *Start is greater than end
# 
# GOAL:
#   Return the primes numbers from the given range
#
# FORMAT:
#   "2 3 5 7 11 13 17 19 ..."
```
# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @max-arias, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
