### ISSUE TITLE
Implement tribonacci

### ISSUE THREAD

**Issue by EByrdS** [rgehan/hacktoberfest-2k18-katas#648]
# tribonacci

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/647

### Where to implement:

`src/tribonacci.js`

### Where are the tests:

`src/tribonacci.test.js`

### Description (optional):

Implement a function that returns the Nth element of a tribonacci sequence.
The positions start counting from one (not zero-based numbering)
The first thee elements of the sequence are: 1, 1, 1

Each element is the sum of the last three number:
ElementN = Element(N-1) + Element(N - 2) + Element(N - 3)

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @nimish-gupta, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
