### ISSUE TITLE
Implement Luhn Check

### ISSUE THREAD

**Issue by max-arias** [rgehan/hacktoberfest-2k18-katas#649]
# Luhn Check

### Link to the PR that adds this test case:

[the url]

### Where to implement:

`src/luhnCheck.js`

### Where are the tests:

`src/luhnCheck.test.js`

### Description (optional):

Validate a credit card number using the Luhn Algorithm

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Delkhaz** [comment]
will tackle this one merged.
/request

**Comment by rgehan** [comment]
Sorry, @Delkhaz, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @Toreilly317, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Toreilly317** [comment]
@max-arias I have a PR ready but I believe the test case has an incorrect test. 

expect(luhnCheck("1234")).toBe('invalid input');

"1234" is valid input but should evaluate to false

I believe the test should be updated to expect(luhnCheck("1234")).toBeFalsy()

**Comment by max-arias** [comment]
@Toreilly317 Good catch. I think you can change it.

**Comment by Toreilly317** [comment]
unfortunately I am not able to pass the PR testing do to the modification needed to the test file. is there a fix for this @rgehan
