### ISSUE TITLE
Implement calculateTrig

### ISSUE THREAD

**Issue by alex-gale** [rgehan/hacktoberfest-2k18-katas#669]
# [Name of the function]

### Link to the PR that adds this test case:

#670 

### Where to implement:

`src/calculateTrig.js`

### Where are the tests:

`src/calculateTrig.test.js`

### Description (optional):

Add a function that accepts one of `'cos', 'sin' or 'tan'` and a number, then returns the result of the respective trigonometric function in radians

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by TiffanieJ** [comment]
/request - Hi I'd like to take on this issue.

**Comment by rgehan** [comment]
Hey @TiffanieJ, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by TiffanieJ** [comment]
Thanks!

**Comment by TiffanieJ** [comment]
Hey @rgehan quick question - my code is passing the test but I see the readme asks for a src/theNewKata.test.js file. What is this?  Thanks!

**Comment by rgehan** [comment]
You have to add a new test, for someone to implement once your PR is merged

**Comment by TiffanieJ** [comment]
thanks - im getting this error when I push ERROR: Permission to rgehan/hacktoberfest-2k18-katas.git denied to TiffanieJ.
fatal: Could not read from remote repository.
