### ISSUE TITLE
pointInTriangle

### ISSUE THREAD

**Issue by MrWako** [rgehan/hacktoberfest-2k18-katas#672]
# pointInTriangle

### Link to the PR that adds this test case:
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/671

### Where to implement:

`src/pointInTriangle.js`

### Where are the tests:

`src/pointInTriangle.test.js`

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @mlukjanska, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @mlukjanska,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by mlukjanska** [comment]
@rgehan did not get around to it yesterday, but am working now, can I get it back?
/request

**Comment by rgehan** [comment]
Hey @mlukjanska, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by MrWako** [comment]
Hi @mlukjanska, I took a little time to get my solution together - just post a comment every <24 hrs to keep the issue.

**Comment by mlukjanska** [comment]
I think I'm up for a solution: https://github.com/mlukjanska/hacktoberfest-2k18-katas/commit/f538636bb65a631c6609c00682180bf42b27a022 (at least the tests are passing). 
Just need to add a new challenge now.

**Comment by mlukjanska** [comment]
@MrWako Thanks, will keep the tips in mind, cool challenge, had to polish off my geometry knowledge :)
