### ISSUE TITLE
Implement `duplicateInArray`

### ISSUE THREAD

**Issue by Delkhaz** [rgehan/hacktoberfest-2k18-katas#68]
### Name of the function

**Where to implement**: `src/duplicateInArray.js`
**Where are the tests**: `src/duplicateInArray.test.js`
**Description**:
Find all the duplicate values in an array

Thanks :heart:

**Comment by rgehan** [comment]
It's merged, you can now implement it

**Comment by srsandy** [comment]
Can i take this.

**Comment by tcelestino** [comment]
@srsandy you can take it.

**Comment by rgehan** [comment]
I've seen no PR, I'll reopen the issue to someone else

**Comment by 2wce** [comment]
can i take this?

**Comment by rgehan** [comment]
Yes go ahead

**Comment by 2wce** [comment]
There's a missing closing bracket in my test which causes Jest to complain. Adding it fixes the issue, can i add the fix as part of my PR?

**Comment by rgehan** [comment]
Yes you should :)
