### ISSUE TITLE
Implement approximately

### ISSUE THREAD

**Issue by shhac** [rgehan/hacktoberfest-2k18-katas#685]
# approximately

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/684

### Where to implement:

`src/approximately.js`

### Where are the tests:

`src/approximately.test.js`

### Description (optional):

`Function<Function<Bool>>`,
* The first function takes a `margin` that specifies how distant any two numbers can be to be considered _"approximately"_ the same
* The returned function takes two numbers and tests if they are "approximately the same"

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @pushpinder107, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @sadarshannaiynar, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by sadarshannaiynar** [comment]
@shhac Can you fix the test cases I think you meant `50000` and not `500000` 😅

**Comment by shhac** [comment]
@sadarshannaiynar oh no, I must've been a little overexcited about typing big numbers!

AFAIK the process here is fix them in a commit on your branch then, after Travis warns you about it, @ the boss rgehan for the merge

**Comment by sadarshannaiynar** [comment]
@shhac Sure no problem :smile:
