### ISSUE TITLE
Implement Dijkstra’s 'shortestPath' algorithm

### ISSUE THREAD

**Issue by karmakaze** [rgehan/hacktoberfest-2k18-katas#710]
# shortestPath

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/711

### Where to implement:

`src/shortestPath.js`

### Where are the tests:

`src/shortestPath.test.js`

### Description (optional):

Use Dijkstra’s algorithm[1] to compute the shortest path from a given `start` node to the given `end` node for the given directed acyclic `graph`. The graph provided has a method `node(label)` which returns a node which in turn has a property `label` and method `adjacent()` which returns a list of `node`s.

[1] https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by DavidSotoA** [comment]
Hi, where is the tests for this issue?

**Comment by karmakaze** [comment]
@DavidSotoA Sorry about that, updated the description adding
link to PR that adds the test https://github.com/rgehan/hacktoberfest-2k18-katas/pull/711

**Comment by rgehan** [comment]
Hey @Di3trich, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
