### ISSUE TITLE
Implement log2 function

### ISSUE THREAD

**Issue by lamnguyen2187** [rgehan/hacktoberfest-2k18-katas#716]
# [log2]

### Link to the PR that adds this test case:

[709](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/709)

### Where to implement:

`src/log2.js`

### Where are the tests:

`src/log2.test.js`

### Description (optional):

Implement a function to return log base 2 of positive numbers. It should return NaN for negative numbers.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @kaikae, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by kaikae** [comment]
@rgehan the test case for this issue is broken: log2(15) simply is not 3 as it is expected in the test. Can I change the test file in this case?
