### ISSUE TITLE
Implement wordWrap

### ISSUE THREAD

**Issue by cyraxx** [rgehan/hacktoberfest-2k18-katas#735]
# wordWrap

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/736

### Where to implement:

`src/wordWrap.js`

### Where are the tests:

`src/wordWrap.test.js`

### Description (optional):

The wordWrap function is given a string and a number of characters. It should word wrap the string into lines of the given maximum length and return those lines as an array of strings. If a single word is too long to fit into the given line length, simply "give up" and have that word on its own on a line that's longer than desired.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Thomasvdam, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
