### ISSUE TITLE
Implement String Interpolation

### ISSUE THREAD

**Issue by PanagiotisGeorgiadis** [rgehan/hacktoberfest-2k18-katas#752]
# [stringInterpolation]

### Link to the PR that adds this test case: 

[#753]

### Where to implement:

`src/stringInterpolation.js`

### Where are the tests:

`src/stringInterpolation.test.js`

### Description (optional):

Implement a string interpolation function following the rules bellow:
    The function gets two arguments, the string and the interpolation values.
    The string interpolation function should search for any interpolation keys ( ie. {1} ) and replace it with
the given interpolation value.

Example:
stringInterpolation("String interpolation is {1}!", [ "exciting" ]);
should return "String interpolation is exciting!"

More info [https://en.wikipedia.org/wiki/String_interpolation](url)
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @cyraxx, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
