### ISSUE TITLE
Implement privToPub

### ISSUE THREAD

**Issue by RomanFro** [rgehan/hacktoberfest-2k18-katas#757]
# privToPub

### Link to the PR that adds this test case:

#756

### Where to implement:

`src/privToPub.js`

### Where are the tests:

`src/privToPub.test.js`

### Description (optional):

This task is based on ECDSA (which is used in many cryptocurrencies and blockchains nowadays; tests for this task are based on Ethereum private/public keys). 
The needed formulas are provided in the `src/privToPub.test.js`. 
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
@RomanFro Could you add more details about your kata?
- What algorithm is it?
- What are the mathematical concepts, etc

**Comment by rgehan** [comment]
Hey @psr1919plus21, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by psr1919plus21** [comment]
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1001
