### ISSUE TITLE
Implement minMaxSum

### ISSUE THREAD

**Issue by Brand-Temp** [rgehan/hacktoberfest-2k18-katas#760]
# minMaxSum

### Link to the PR that adds this test case:

#761 

### Where to implement:

`src/minMaxSum.js`

### Where are the tests:

`src/minMaxSum.test.js`

### Description (optinal)

Implement an algorithm which sums the smallest and largest numbers in an array.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by eduenriquez** [comment]
hi ✋ can i take this ? @Brand-Temp

**Comment by rgehan** [comment]
Hey @eduenriquez, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @eduenriquez,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @rinkevich, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by cori** [comment]
I'd be interested in implementing this kata, but the test cases don't make sense to me.

For instance in the final test case, minMaxSum of the smallest and largest numbers in `[10, 6, 23, 7, 12, -4, 0, -12]` it seems like the sum of the smallest (`-12`) and largest (`23`) numbers should be `11`, not `13`. And for the last case the minMaxSum of `[-1, -5, -20, -6, -9]` seems like it should be `-21`, not `-12`.

So I'm afraid either I misunderstand the requirements of the kata or my solution wouldn't pass the tests.
