### ISSUE TITLE
Implement `ifZero`

### ISSUE THREAD

**Issue by rgehan** [rgehan/hacktoberfest-2k18-katas#77]
### ifZero

**Where to implement**: `src/ifZero.js`
**Where are the tests**: `src/ifZero.test.js`

Thanks :heart:

**Comment by moogacs** [comment]
ifZero do what ?

**Comment by Delkhaz** [comment]
if no one is assigned ill take it

**Comment by rgehan** [comment]
It seems to sum its parameters and check if their sum is 0.

https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/src/ifzero.test.js

**Comment by moogacs** [comment]
I will take it ? 
@Delkhaz

**Comment by rgehan** [comment]
Yep you were there first, go ahead

**Comment by Delkhaz** [comment]
yea, no problem ! @moogacs
