### ISSUE TITLE
Implement `isHarshad`

### ISSUE THREAD

**Issue by AntonStrand** [rgehan/hacktoberfest-2k18-katas#78]
### isHarshad

**Where to implement**: `src/isHarshad.js`
**Where are the tests**: `src/isHarshad.test.js`
**Description**:
Validate if a number is a Harshad number with the base of 10. 
The sum of the digits should be divisible by the number.

e.g.
`24, because 2 + 4 = 6 and 24 = 6 × 4`
`198, because 1 + 9 + 8 = 18 and 198 = 18 × 11`

Thanks :heart:

**Comment by rgehan** [comment]
Could you make a PR with the relevant test cases? :)

**Comment by AntonStrand** [comment]
Here you go https://github.com/rgehan/hacktoberfest-2k18-katas/pull/79

**Comment by Delkhaz** [comment]
once merged ill tackle this

**Comment by rgehan** [comment]
Go ahead @Delkhaz

**Comment by rgehan** [comment]
I've seen no PR in the last 11h, I'll deassign you

**Comment by cptjacky** [comment]
I'm taking that one 🐵
