### ISSUE TITLE
Implement countCoprimes

### ISSUE THREAD

**Issue by Di3trich** [rgehan/hacktoberfest-2k18-katas#789]
# countCoprimes

### Link to the PR that adds this test case:

#788 

### Where to implement:

`src/countCoprimes.js`

### Where are the tests:

`src/countCoprimes.test.js`

### Description (optional):

Given an integer `N` count all **coprimes** of `N` less than itself.  Two integers `a` and `b` are said to be **relatively prime**, **mutually prime**, or **coprime** (also written co-prime) if the only positive integer (factor) that divides both of them is `1`, This is equivalent to say, if the greatest common divisor (gcd) of `a` and `b` is `1` then `a` and `b` are coprime numbers.

#### Examples
`countCoprimes(4) => 2`
The coprimes of `4` less than itself are: `1` and `3`.

`countCoprimes(10) => 4`
The coprimes of `10` less than itself are: `1`, `3`, `7` and `9`.

`countCoprimes(11) => 10`
The coprimes of `11` less than itself are: `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9` and `10`.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @AkulG1, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @AkulG1,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @shivanggarg1998, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by Zeroji** [comment]
Hey @rgehan there was an issue with this issue #789 and my issue for prefixSum #815 
@shivanggarg1998 implemented countCoprimes (this issue) in PR #820 but accidentally referenced #815, the Travis check passed the countCoprimes tests but the Github bot closed prefixSum (which isn't implemented) instead due to the bugged reference

**Comment by shivanggarg1998** [comment]
Sorry for that , I have edited the PR #820  and I have implemented Prefix Sum function #822 and closed this issue.
