### ISSUE TITLE
Implement coinWays

### ISSUE THREAD

**Issue by iambk** [rgehan/hacktoberfest-2k18-katas#796]
# coinWays

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/797

### Where to implement:

`src/coinWays.js`

### Where are the tests:

`src/coinWays.test.js`

### Description (optional):

Given different types of coins available to you in infinite quantities. The value of each coin is already given. Determine the number of ways of making change for a particular number of units using the given types of coins?

For example, if you have 4 types of coins, and the value of each type is given as 8, 3, 1, 2 respectively, you can make change for 3 units in three ways: {1, 1, 1}, {1, 2}, and {3}.

Input Format: (n, m, c), n: number of units, m: number of coin types, c: value of each coin type

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Zeroji, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
