### ISSUE TITLE
Implement `decimalToBinary`

### ISSUE THREAD

**Issue by srsandy** [rgehan/hacktoberfest-2k18-katas#80]
### decimalToBinary

**Where to implement**: `src/decimalToBinary.js`
**Where are the tests**: `src/decimalToBinary.test.js`
**Description**:
Converts a Decimal number ( base 10 ) to a Binary number ( base 2 ).

Thanks :heart:

**Comment by johnnymetz** [comment]
Is this assigned or can I take it?

**Comment by srsandy** [comment]
#85 done 👍

**Comment by srsandy** [comment]
If no one solves this add the task for me

**Comment by johnnymetz** [comment]
Done: https://github.com/rgehan/hacktoberfest-2k18-katas/pull/89
