### ISSUE TITLE
Implement lisp (a mini Lisp interpreter)

### ISSUE THREAD

**Issue by bigblind** [rgehan/hacktoberfest-2k18-katas#800]
# lisp

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/799

### Where to implement:

`src/<lisp>.js`

### Where are the tests:

`src/<lisp>.test.js`

### Description (optional):

The function should take an expression as a string, evaluate it, and return the result.

You should accept expressions of the following forms:
 - "42": A single positive integer
 - "(add 19 23)" A function call. A function call is a space-separated list of expressions, between brackets. The first element of the list is the function name.

Your program should accept the following functions:

- "(add a b)" returns a + b
- "(sub a b)" returns a - b
- "(mul a b)" returns a * b
- "(div a b)" returns a / b
- "(sqrt a)" returns the square root of x.

Function calls can be nested, so for example, the expression "(add (mul 2 3) (sub 8 3))" should return 11.
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @Zeroji, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
