### ISSUE TITLE
Implement Xbonacci

### ISSUE THREAD

**Issue by EByrdS** [rgehan/hacktoberfest-2k18-katas#825]
# xbonacci

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/824

### Where to implement:

`src/xbonacci.js`

### Where are the tests:

`src/xbonacci.test.js`

### Description (optional):

This function is the general case for classic Fibonacci. The initial elements are provided in `seed` (in Fibonacci, the `seed` is: `[1, 1]`). The nth element is asked in the second argument `position`.

For example: Fibonacci(3) = Xbonacci([1, 1], 3) = 2

Each element is the sum of its previous elements, depending on the length of the seed. (i.e. if the seed is `[1, 1, 1]` then each element is the sum of its previous 3 elements, and so on)

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @jeanbenitez, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
