### ISSUE TITLE
Implement 'firstCharacterInString'

### ISSUE THREAD

**Issue by lourdesr** [rgehan/hacktoberfest-2k18-katas#83]
### firstCharacterInString

**Link to the PR that adds this test case**: [https://github.com/rgehan/hacktoberfest-2k18-katas/pull/81]
**Where to implement**: `src/firstCharacterInString.js`
**Where are the tests**: `src/firstCharacterInString.test.js`
**Description**:
Given an input string, return a list that contains all the first characters in the string.
Example:
Input:
Hello World
Output:
['H','W']

Thanks :heart:

**Comment by fritzlolpro** [comment]
I'll do it

**Comment by rgehan** [comment]
You go ahead

**Comment by fritzlolpro** [comment]
https://github.com/rgehan/hacktoberfest-2k18-katas/pull/88
done
