### ISSUE TITLE
Implement `longestWord`

### ISSUE THREAD

**Issue by Waddas** [rgehan/hacktoberfest-2k18-katas#84]
### longestWord

**Link to the PR that adds this test case**: [#82](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/82)
**Where to implement**: `src/longestWord.js`
**Where are the tests**: `src/longestWord.test.js`

Thanks :heart:

**Comment by rbadr** [comment]
I'll take it :)

**Comment by rgehan** [comment]
Go ahead!
