### ISSUE TITLE
Returns the number of elements deletions required

### ISSUE THREAD

**Issue by bedis-elacheche** [rgehan/hacktoberfest-2k18-katas#852]
# elementsDeletion

### Link to the PR that adds this test case:

#853

### Where to implement:

`src/elementsDeletion.js`

### Where are the tests:

`src/elementsDeletion.test.js`

### Description (optional):

Returns the number of elements deletions required to make a and b contain the same exact letters in the same exact frequency.
`elementsDeletion('bacdc', 'dcbac')` returns 0
    the strings have the same exact letters in the same exact frequency, no deletions needed
 
`elementsDeletion('bacdc', 'dcbad')` returns 2
    we have to remove one 'c' from a and one 'd' from b

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @leodevo, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @leodevo, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by leodevo** [comment]
@rgehan @bedis-elacheche  I think there is an error in the test file, 
all the tests are in the form : "expect(() => elementsDeletion([1, 2, 3, 4], [4, 1, 2])).toEqual(1);"
but if the test is not supposed to throw, it should only be : "expect(elementsDeletion([1, 2, 3, 4], [4, 1, 2])).toEqual(1);" meaning withouth the "**() =>**" part. 
If I'm right, shall I modify it in my own PR ? 
Anyway, I might be wrong, let me know.

**Comment by bedis-elacheche** [comment]
@leodevo my bad! x)
