### ISSUE TITLE
Implement `repeat`

### ISSUE THREAD

**Issue by ivansieder** [rgehan/hacktoberfest-2k18-katas#86]
### repeat

**Link to the PR that adds this test case**: https://github.com/rgehan/hacktoberfest-2k18-katas/pull/39
**Where to implement**: `src/repeat.js`
**Where are the tests**: `src/repeat.test.js`

Thanks :heart:

**Comment by lchaglla** [comment]
I'll take it

**Comment by rgehan** [comment]
You go ahead (wait for #39 to be merged though)
