### ISSUE TITLE
Count number of characters in a given string 

### ISSUE THREAD

**Issue by gihanmu** [rgehan/hacktoberfest-2k18-katas#879]
# [numberOfChars]

### Link to the PR that adds this test case:

[Link](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/880)

### Where to implement:

`src/numberOfChars.js.js`

### Where are the tests:

`src/<umberOfChars.test.js`

### Description (optional):

Count the number of characters in a given string 

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @kallerdaller, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
