### ISSUE TITLE
animalSort

### ISSUE THREAD

**Issue by Qwetuo** [rgehan/hacktoberfest-2k18-katas#881]
# animalSort

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/882

### Where to implement:

`src/animalSort.js`

### Where are the tests:

`src/animalSort.test.js`

### Description (optional):

Write a method that accepts an array of objects (example below), and returns a new array.
The new array should be a copy of the original list, sorted first by the animal's number of legs, and then by its name.

Example of input:
const animal = [
{ name: "Cat", numberOfLegs: 4 },
{ name: "Snake", numberOfLegs: 0 },
{ name: "Dog", numberOfLegs: 4 },
{ name: "Pig", numberOfLegs: 4 },
{ name: "Human", numberOfLegs: 2 },
{ name: "Bird", numberOfLegs: 2 }
]

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @qwewrty, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
