### ISSUE TITLE
3-Sum

### ISSUE THREAD

**Issue by babhishek21** [rgehan/hacktoberfest-2k18-katas#897]
# 3-Sum (a.k.a `threeSum`)

### Link to the PR that adds this test case:

#896 

### Where to implement:

`src/threeSum.js`

### Where are the tests:

`src/threeSum.test.js`

### Description (optional):

Given an array of numbers and a target sum, find the first triplet that adds up to the target. If there is no such triplet, return null. Throw when you get invalid inputs.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @SamirHodzic, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by SamirHodzic** [comment]
@babhishek21 @rgehan test cases for invalid inputs are not defined properly. They should be as 

```javascript
 expect(() => threeSum([], 35)).toThrow();
```

not as they are currently defined

```javascript
expect(threeSum([], 35)).toThrow();
```
