### ISSUE TITLE
Implement `reverseString`

### ISSUE THREAD

**Issue by johnnymetz** [rgehan/hacktoberfest-2k18-katas#90]
### Name of the function

**Link to the PR that adds this test case**:  #89 
**Where to implement**: `src/revereString.js`
**Where are the tests**: `src/reverseString.test.js`
**Description**: Reverse a string (e.g. `"hello"` -> `"olleh"`)

Thanks :heart:

**Comment by Sergeytroinin** [comment]
I'm on it

**Comment by kumaran-14** [comment]
Next in line

**Comment by Tassion** [comment]
Hmm, no update ? Can I take this one ?

**Comment by Sergeytroinin** [comment]
Sorry for delay. Here is PR for it: #122
