### ISSUE TITLE
implement addRoman

### ISSUE THREAD

**Issue by jessmear** [rgehan/hacktoberfest-2k18-katas#905]
# addRoman

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/906

### Where to implement:

`src/addRoman.js`

### Where are the tests:

`src/addRoman.test.js`

### Description (optional):

Add Roman numerals given to the function as a string with spaces separating the numerals. 

- Accept any number of numerals. 
- Accept lower case. 
- Reject alternative forms of Roman numerals (ex: IIII as 4) 
- Reject empty strings, numbers, strings that have characters outside what is expected for Roman numerals, and hex numbers.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @SamirHodzic, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
