### ISSUE TITLE
PickPeaks (Maxima Local)

### ISSUE THREAD

**Issue by emirpolo** [rgehan/hacktoberfest-2k18-katas#915]
# pickPeaks

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/916

### Where to implement:

`src/pickPeaks.js`

### Where are the tests:

`src/pickPeaks.test.js`

### Description (optional):

```
Write a function that returns the positions and the values of the "peaks" (or local maxima) of a numeric array.
The output will be returned as an object with two properties: pos and peaks. Both of these properties should be arrays.
If there is no peak in the given array, then the output should be {pos: [], peaks: []}.
The first and last elements of the array will not be considered as peaks (in the context of a mathematical function,
we don't know what is after and before and therefore, we don't know if it is a peak or not).
```

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @rahulchanglani, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
