### ISSUE TITLE
Check if the given number is Hoax or not

### ISSUE THREAD

**Issue by dineshvgp** [rgehan/hacktoberfest-2k18-katas#918]
# isHoaxNumber

### Link to the PR that adds this test case:

#917

### Where to implement:

`src/isHoaxNumber.js`

### Where are the tests:

`src/isHoaxNumber.test.js`

### Description (optional):

Given a number ‘n’, check whether it is a hoax number or not.

A Hoax Number is defined as a composite number, whose sum of digits is equal to the sum of digits of its distinct prime factors. It may be noted here that, 1 is not considered a prime number, hence it is not included in the sum of digits of distinct prime factors.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @rahulchanglani, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
