### ISSUE TITLE
Implement `countCharacter`

### ISSUE THREAD

**Issue by lchaglla** [rgehan/hacktoberfest-2k18-katas#92]
### Name of the function

**Link to the PR that adds this test case**:  https://github.com/rgehan/hacktoberfest-2k18-katas/pull/93
**Where to implement**: `src/countCharacter.js`
**Where are the tests**: `src/countCharacter.test.js`

Thanks :heart:

**Comment by shotozuro** [comment]
I'll take it.. 👍

**Comment by shotozuro** [comment]
done [#119](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/119)

**Comment by shotozuro** [comment]
I've opened new PR [#138](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/138) but there's a typo in the countCharacter test file from PR [#93](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/93). It causes my code failed to test.
