### ISSUE TITLE
Implement `isDivisibleByThree` 

### ISSUE THREAD

**Issue by rbadr** [rgehan/hacktoberfest-2k18-katas#95]
### isDivisibleByThree

**Link to the PR that adds this test case**: https://github.com/rgehan/hacktoberfest-2k18-katas/pull/94
**Where to implement**: `src/isDivisibleByThree.js`
**Where are the tests**: `src/isDivisibleByThree.test.js`
**Description**:
```
333 -> True
'792' -> True
22 -> false
```

Thanks :heart:

**Comment by lchaglla** [comment]
Ill take it

**Comment by bsztankovacs** [comment]
next in line

**Comment by kumaran-14** [comment]
I ll take this?

**Comment by bsztankovacs** [comment]
Can I have it, as I volunteered before kumuran-14?

**Comment by cptjacky** [comment]
@kumaran-14 has been assigned another one already.

I'm assigning that one to you @bsztankovacs :)

**Comment by rgehan** [comment]
Reopened as it seems to be stale.

**Comment by VickyKoblinski** [comment]
I'll take it
