### ISSUE TITLE
nameMatrix

### ISSUE THREAD

**Issue by SamirHodzic** [rgehan/hacktoberfest-2k18-katas#950]
# nameMatrix

### Link to the PR that adds this test case:

[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/949]

### Where to implement:

`src/nameMatrix.js`

### Where are the tests:

`src/nameMatrix.test.js`

### Description (optional):

```
Given a name, turn that name into a perfect square matrix 
(nested array with the amount of arrays equivalent to the length of each array).
You will need to add `-` to the end of the name if necessary, to turn it into a matrix.
```
---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by surmistry** [comment]
Is this still open? I'd like to take a swing at it

**Comment by SamirHodzic** [comment]
@surmistry just write `/request` as comment, and it will be assigned to you.

**Comment by rgehan** [comment]
Hey @surmistry, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by surmistry** [comment]
I'm assuming the test case in place is sufficient and didn't make my own, so I left unchecked. Please advise

**Comment by SamirHodzic** [comment]
Please read description of this issue from part `If you want to take on this issue:`.
You need to add test cases for new kata ([README.md](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md)).

**Comment by surmistry** [comment]
This looks like it's a readme for create new kata, not implementing someone else's?

**Comment by surmistry** [comment]
Oh, interesting, each implementation needs to create a new kata?

**Comment by SamirHodzic** [comment]
Exactly 😄
