### ISSUE TITLE
Implement stopApologizing

### ISSUE THREAD

**Issue by surmistry** [rgehan/hacktoberfest-2k18-katas#960]
# [stopApologizing]

### Link to the PR that adds this test case:

#955 

### Where to implement:

`src/<stopApologizing>.js`

### Where are the tests:

`src/<stopApologizing>.test.js`

### Description (optional):

If the function is complex enough to warrant a description, add it here...

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Hey @pckhib, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by pckhib** [comment]
@surmistry There's an error in the test file [line 9](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/b901a7b12e8cb97d8e348c931399dcca11b2ecbd/src/stopApologizing.test.js#L9).
An closing bracket right before `.toEqual` is missing

**Comment by rgehan** [comment]
Hey @pckhib,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @pckhib,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @pckhib,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by rgehan** [comment]
Hey @pckhib,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by GaryPWhite** [comment]
@surmistry @rgehan there's a bit of a typo in the test, line 9

https://github.com/rgehan/hacktoberfest-2k18-katas/blob/0d7ef4bd126e7da5f8e0ae7729044797a704f13e/src/stopApologizing.test.js#L9

ought to have an extra parenthesee before calling .toEqual(). Throws an error otherwise. Let me know if we can get this resolved 👍

**Comment by GaryPWhite** [comment]
also, @pckhib seems to have pointed this out, and I'm alright with having the issue reverted to him for credit on his PR. I understand there was a lot of issues with Github today and last night, so I think it might have been lost in that shuffle.

**Comment by rgehan** [comment]
Hey @GaryPWhite,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot

**Comment by GaryPWhite** [comment]
alright, i'll take it up again

**Comment by rgehan** [comment]
Hey @GaryPWhite, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by GaryPWhite** [comment]
and there's still this bug... @surmistry pls

**Comment by rgehan** [comment]
Hey @GaryPWhite,

It looks like this issue has been inactive for at least 24 hours.

An issue is considered inactive if:
- You, the assignee, didn't comment on it during the period described above
- You, the assignee, didn't open a PR related to the issue (for it to be considered as related, the ID of the issue needs to appear either in the title of the PR, or in its body. Don't forget the # symbol before).

If you think this is an error, please ping me in your reply.

/reset

##### This was automatically generated by a bot
