### ISSUE TITLE
Implement unusedNumbers

### ISSUE THREAD

**Issue by taverasmisael** [rgehan/hacktoberfest-2k18-katas#961]
# unusedNumbers

### Link to the PR that adds this test case:

[Pull Request](https://github.com/rgehan/hacktoberfest-2k18-katas/pull/957)

### Where to implement:

`src/unusedNumbers.js`

### Where are the tests:

`src/unusedNumbers.test.js`

### Description (optional):

A function that takes any number of integer parameters and returns a string containing (in order) all the integer numbers not used in any of the parameters. Check the test cases

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @rahulchanglani, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @gihanmu, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.
