### ISSUE TITLE
calculate Rectangle areas

### ISSUE THREAD

**Issue by taverasmisael** [rgehan/hacktoberfest-2k18-katas#963]
# calculateRectangleAreas

### Link to the PR that adds this test case:

#962

### Where to implement:

`src/calculateRectangleAreas.js`

### Where are the tests:

`src/calculateRectangleAreas.test.js`

### Description (optional):

Given a 2D array of numbers (rectangle measurements) calculate its area returning a single dimension array with the results for each pair

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry, @rahulchanglani, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @VivekSingh777, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by VivekSingh777** [comment]
Test Case for this are wrong.
expect(calculateRectangleAreas([[3, 4]])).isEqual([12])
expect(calculateRectangleAreas([[3,4], [8, 10]])).isEqual([12, 80])
expect(calculateRectangleAreas([[1,2], [4, 2], [8, 18], [12, 5]])).isEqual([2, 8, 144, 60])

**Comment by VivekSingh777** [comment]
@rgehan Why we are throwing error in Success case

**Comment by taverasmisael** [comment]
@VivekSingh777 my bad man, your correction is totally right, in the success cases should be ```.isEqual``` not ```.toThrow```. You can upload the changes in your PR

**Comment by VivekSingh777** [comment]
@rgehan Will u look at the above PR. It can not be automatically merge
