### ISSUE TITLE
Move zeroes to end

### ISSUE THREAD

**Issue by rahulchanglani** [rgehan/hacktoberfest-2k18-katas#970]
# moveZerosToEnd

### Link to the PR that adds this test case:

[https://github.com//pull/914]

### Where to implement:

`src/moveZerosToEnd.js`

### Where are the tests:

`src/moveZerosToEnd.test.js`

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @adamxtokyo, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @V1shvesh, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by V1shvesh** [comment]
Hey @rgehan

I'm trying to merge my PR, but I get this message : 

![screenshot_2018-10-22 finished movezerostoend and created addmatrix by v1shvesh pull request 972 rgehan hacktoberfest-](https://user-images.githubusercontent.com/22243137/47284469-1d539e80-d605-11e8-95d7-a9bde3f2fb99.png)
