### ISSUE TITLE
addMatrix

### ISSUE THREAD

**Issue by V1shvesh** [rgehan/hacktoberfest-2k18-katas#973]
# [addMatrix]

### Link to the PR that adds this test case:

[https://github.com/rgehan/hacktoberfest-2k18-katas/pull/972]

### Where to implement:

`src/addMatrix.js`

### Where are the tests:

`src/addMatrix.test.js`

### Description (optional):

Takes two matrices of equal dimensions as input and outputs the sum of both matrices.

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by Lolechi** [comment]
Are the matrices simply two 2-dimensional arrays? Either way /request

**Comment by rgehan** [comment]
Sorry @Lolechi, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by nfatma** [comment]
I am working on it.

**Comment by nfatma** [comment]
i am almost done

**Comment by nfatma** [comment]
@V1shvesh can you please modify the test cases as suggested [https://github.com/rgehan/hacktoberfest-2k18-katas/pull/1049#issuecomment-433532380](here).

**Comment by nfatma** [comment]
@V1shvesh can you please modify the test cases (by removing the arrow functions in expect).
